Observability build
canonical-web-and-design/ubuntu.com pull request #10105
Opened 2021-07-30 10:11 UTC by petesfrench

## Done

- [ ] Built Oberservability page

- [ ] Built Observability form

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/observability
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare page against [copy-doc](https://docs.google.com/document/d/1NxJdT3BD6EWnpsu-eathNyranQVImnDGhuCjzsIWh4s/edit#)
- **NOTE: Not ready for review, waiting on contact form**

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4242

2021-07-30 10:28 UTC, petesfrench commented
DEMO: https://ubuntu-com-10105.demos.haus/observability

2021-07-30 10:52 UTC, spencerbygraves commented
Thanks @petesfrench, a couple of things...

- Can you make the subtitle "Observability with open source..." h2 please
- Two images are missing here:
![image](https://user-images.githubusercontent.com/9105999/127640720-b6746420-e310-4b48-ac6c-80b678aa381e.png)
- Can we give the 3 logo headers the same colour and spacing please, the second one looks about right:
![image](https://user-images.githubusercontent.com/9105999/127641068-6a3a7193-a50e-4049-aeaa-41b3be505691.png)
- Can you use [this Openstack logo](https://assets.ubuntu.com/v1/5a3b2944-Openstack-logo-2021.svg) in the last logo section please
- It looks like the bullet points in the last section are [the indented style](https://vanillaframework.io/docs/examples/base/lists/unordered-list), can they be the solid ones please

Thanks.

2021-07-30 13:43 UTC, petesfrench commented
> * It looks like the bullet points in the last section are [the indented style](https://vanillaframework.io/docs/examples/base/lists/unordered-list), can they be the solid ones please

@sowasred2012 Hey Scott, is there a way this can be acheived, as the list needs to be nested within the list of the parent matrix?

2021-07-30 14:55 UTC, petesfrench commented
@spencerbygraves How important is it that the bullet points are not in the indented style? It is possible but would be a bit hacky..

2021-08-02 08:23 UTC, sowasred2012 requested changes
We should be using the image template for all images, it helps keep pages performant - check out [this discourse doc](https://discourse.ubuntu.com/t/editor-tricks/14448) if you haven't already, you can add a code snippet to VS code that makes adding image template blocks really easy.

2021-08-02 08:23 UTC, sowasred2012 commented on templates/observability/index.html
> +          loading="lazy"
This image is "above the fold", so this value shoud be `auto` or `eager`, to reduce the chance of layout shift when the image loads. See `image-template` [docs](https://github.com/canonical-web-and-design/canonicalwebteam.image-template#parameters)

2021-08-02 08:23 UTC, sowasred2012 commented on templates/observability/index.html
> +          <img class="p-heading-icon__img" src="https://assets.ubuntu.com/v1/826d5be3-1200px-Prometheus_software_logo.svg.png" alt="">
All of these images should use the image template

2021-08-02 08:23 UTC, sowasred2012 commented on templates/observability/index.html
> +        <img class="p-matrix__img" src="https://assets.ubuntu.com/v1/3b176ef1-managed-private-cloud.svg" alt="">
These too should use the image template

2021-08-02 08:23 UTC, sowasred2012 commented on templates/observability/index.html
> +        <img class="p-matrix__img" src="https://assets.ubuntu.com/v1/7de21966-snapshot.svg" alt="">
Same thing - image template, rather than img tags

2021-08-02 11:01 UTC, pmahnke commented
@petesfrench also, the asset server also has image tags to copy 

![image](https://user-images.githubusercontent.com/441217/127851687-3aab3b52-b237-43f0-8721-903a5ee064ad.png)

2021-08-02 11:12 UTC, sowasred2012 commented
> @petesfrench also, the asset server also has image tags to copy
> 
> ![image](https://user-images.githubusercontent.com/441217/127851687-3aab3b52-b237-43f0-8721-903a5ee064ad.png)

:exploding_head: didn't know that! Very cool.

2021-08-02 14:24 UTC, petesfrench commented
@sowasred2012 Thank you for the feedback, I have made those changes now

2021-08-02 14:38 UTC, sowasred2012 reviewed
@petesfrench almost there - one grammar thing, and a tweak to the lists, it's my fault for not mentioning @spencerbygraves had requested these lists be `is-ticked`, apologies

2021-08-02 14:38 UTC, sowasred2012 commented on templates/observability/index.html
> +      <h2 class="u-align--center p-logo-section__title">A SELECTION OF SUPPORTED OPEN SOURCE MONITORING TOOLS AND DASHBOARDS</h2>
```suggestion
      <h2 class="u-align--center p-logo-section__title">A selection of supported open source monitoring tools and dashboards</h2>
```

2021-08-02 14:38 UTC, sowasred2012 commented on templates/observability/index.html
> +      </ul>
```suggestion
      <ul class="p-list">
        <li class="p-list__item is-ticked">You drive the business, we maintain the monitoring tools</li>
        <li class="p-list__item is-ticked">Put DevOps on-rails with high quality observability</li>
        <li class="p-list__item is-ticked">Expand globally, without needing a global team</li>
      </ul>
```

2021-08-02 14:38 UTC, sowasred2012 commented on templates/observability/index.html
> +      </ul>
```suggestion
      <ul class="p-list">
        <li class="p-list__item is-ticked">Reduce human-error</li>
        <li class="p-list__item is-ticked">Automated at scale</li>
        <li class="p-list__item is-ticked">Powered by <a class="p-link--external" href="https://juju.is/">Juju</a></li>
        <li class="p-list__item is-ticked">Managed by app-specific experts</li>
      </ul>
```

2021-08-02 14:38 UTC, sowasred2012 commented on templates/observability/index.html
> +      </ul>
```suggestion
      <ul class="p-list__item">
        <li class="p-list__item is-ticked">Per-machine price</li>
        <li class="p-list__item is-ticked">Multiple portfolio apps, no extra cost</li>
        <li class="p-list__item is-ticked">Unlimited usage</li>
        <li class="p-list__item is-ticked">Transfer management back on request</li>
      </ul>
```

2021-08-02 14:38 UTC, sowasred2012 commented on templates/observability/index.html
> +      </ul>
```suggestion
      <ul class="p-list">
        <li class="p-list__item is-ticked">Bring your own cloud</li>
        <li class="p-list__item is-ticked">The latest open source dashboards and tools, today, without hiring delays</li>
        <li class="p-list__item is-ticked">Offload resource-intensive operations to our specialist team</li>
      </ul>
```

2021-08-03 13:09 UTC, spencerbygraves commented
@petesfrench thanks for the updates 👍

2021-08-03 14:15 UTC, pmahnke requested changes
getting there... some comments below

2021-08-04 09:41 UTC, mmanciop commented
- There is a *lot* of whitespace between sections, e.g., above `TRUSTED BY`.
- I am a bit surprised to see the `A SELECTION OF SUPPORTED OPEN SOURCE MONITORING TOOLS AND DASHBOARDS` section on a different background than the item above that it belongs to, namely "Reliable monitoring tools you can count on"
- There is a `[ Request a free deployment assessment  ]` missing below the `OPTIMISE YOUR OPEN SOURCE OBSERVABILITY` header

2021-08-04 09:42 UTC, mmanciop commented
I am also not sold on the line breaks (`<hr class="p-separator"/>`) in between most sections

2021-08-04 09:52 UTC, mmanciop commented
Finally, I realize the design in Google Docs misses a "final Get in touch with us" CTA, I made a few updates to the [Google Doc](https://docs.google.com/document/d/1NxJdT3BD6EWnpsu-eathNyranQVImnDGhuCjzsIWh4s/edit#). The changes are: the final "closing" section, and some minor changes to the headers inside the "Managed monitoring tools, anywhere" section.

2021-08-04 09:52 UTC, mmanciop commented
Finally, I realize the design in Google Docs misses a "final Get in touch with us" CTA, I made a few updates to the [Google Doc](https://docs.google.com/document/d/1NxJdT3BD6EWnpsu-eathNyranQVImnDGhuCjzsIWh4s/edit#). The changes are: the final "closing" section, and some minor changes to the headers inside the "Managed monitoring tools, anywhere" section.

2021-08-04 09:53 UTC, mmanciop commented
Overall, can I please be added as reviewer? :-)

2021-08-04 09:56 UTC, mmanciop commented
I just clicked on the contact form and... well, it does not look right folks.
![Screenshot from 2021-08-04 11-55-13](https://user-images.githubusercontent.com/14020598/128161707-5632d0aa-1e43-455f-81d9-2e8dda300a74.png)

2021-08-04 09:59 UTC, mmanciop commented
The last page of the contact form also has a rather strange flow when compared to other contact forms, say, the OpenStack one: https://ubuntu.com/openstack#get-in-touch

![Screenshot from 2021-08-04 11-57-14](https://user-images.githubusercontent.com/14020598/128162085-ee00ab2b-bca0-416a-b6d9-2c0a360577ec.png)

2021-08-04 10:53 UTC, petesfrench commented
@spencerbygraves What do you think of the design suggestions from @mmanciop ?

2021-08-04 11:30 UTC, spencerbygraves commented
@mmanciop

> There is a lot of whitespace between sections, e.g., above TRUSTED BY.

We use strips that come with different amounts of padding, we'll have another look at which ones to use.

> I am a bit surprised to see the A SELECTION OF SUPPORTED OPEN SOURCE MONITORING TOOLS AND DASHBOARDS section on a different background than the item above that it belongs to, namely "Reliable monitoring tools you can count on"

That wasn't completely clear from the copy doc but I will update the design.

> I am also not sold on the line breaks...

We use these to either clearly separate content, or give structure to related content.

> In the contact form and the padding around the listy items does look much larger than some other contact forms with comparable structure.

I agree it could be improved, we'll update it to be more like this one - https://ubuntu.com/openstack/managed#get-in-touch

2021-08-05 08:05 UTC, mmanciop commented
> @mmanciop
> 
> > There is a lot of whitespace between sections, e.g., above TRUSTED BY.
> 
> We use strips that come with different amounts of padding, we'll have another look at which ones to use.
 
Thanks!

> > I am a bit surprised to see the A SELECTION OF SUPPORTED OPEN SOURCE MONITORING TOOLS AND DASHBOARDS section on a different background than the item above that it belongs to, namely "Reliable monitoring tools you can count on"
> 
> That wasn't completely clear from the copy doc but I will update the design.

I would be very interested in understanding the best practices for the Google Docs, so that I can make it clearer the next time. How would I have documented something like this?

> > I am also not sold on the line breaks...
> 
> We use these to either clearly separate content, or give structure to related content.

I understand the rationale; my remark, admittedly poorly worded, was more in the direction of finding the amount of separation too large for things that were related with one another. I can leave some comments in the HTML for which separators I found, well, too successful at separating, I guess :D

> > In the contact form and the padding around the listy items does look much larger than some other contact forms with comparable structure.
> 
> I agree it could be improved, we'll update it to be more like this one - https://ubuntu.com/openstack/managed#get-in-touch

2021-08-05 08:40 UTC, mmanciop commented on templates/observability/index.html
> +    <hr class="p-separator" />
This separator feels a bit too large, as we are qualifying with the grid below why it is a good idea for the prospect to get their monitoring tools to be run by Canonical

2021-08-05 08:41 UTC, mmanciop commented on templates/observability/index.html
> +    <hr class="p-separator" />
This separator feels too large, the "We run your monitoring tools anywhere" is substantiated by the logos of all the places we do that, and now it feels too far away in the page

2021-08-05 14:16 UTC, mmanciop commented on templates/observability/index.html
> +  <div class="row">
@petesfrench, please add here:

```
<p class="p-logo-section__title u-align--center">Open source monitoring you can lean on</p>
```

As per https://docs.google.com/document/d/1NxJdT3BD6EWnpsu-eathNyranQVImnDGhuCjzsIWh4s/edit#heading=h.d8od1qesrheo

2021-08-05 15:59 UTC, sowasred2012 approved these changes
LGTM

2021-08-05 16:05 UTC, merged