Copy update on /security/docker-images
canonical-web-and-design/ubuntu.com pull request #10311
Opened 2021-09-06 13:06 UTC by minkyngkm

## Done
- Updated the page title 
- Updated `LTS Docker Images` to `Long Term Supported OCI Images`
- Added a code block and created the `typer.js`file  in the`js/dist` to make the code block animated.
- Added a link with "Explore our CVE-fixing track record >" 
- Added `Contact` and `Get in touch` and linked them to the contact form.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/docker-images
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Please check page against [copy doc](https://docs.google.com/document/d/1zZibtjU141e4mBxo_0PtfYxJ6e5fyaaAdFZ6v945XAM/edit) and resolve comments

## Issue / Card

Fixes [#4402](https://github.com/canonical-web-and-design/web-squad/issues/4402#event-5260114797)

## Screenshots

![image](https://user-images.githubusercontent.com/57550290/132221723-56e0faca-4a69-4ef5-bbb9-87415de610fa.png)

2021-09-06 13:06 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10311.demos.haus

2021-09-06 13:19 UTC, valentincanonical commented
Thanks for being so quick! I have a few comments, if I may: 

- The code snippet animation doesn't seem to work (Firefox 88.0.1 on Ubuntu)
![Screenshot 2021-09-06 at 15 14 39](https://user-images.githubusercontent.com/74904857/132222964-f637429d-dc0f-4169-bf08-5cae90d17630.png)
Beyond fixing the issue, I believe there should be a default placeholder in case the animation does not work (for whatever reason). 

- Section "Our commitment", 'Designed for layering - “FROM public.ecr.aws/lts/mysq"' there's a "L" missing at the end of MySQL, should be, 'Designed for layering - “FROM public.ecr.aws/lts/mysql”'
![Screenshot 2021-09-06 at 15 18 11](https://user-images.githubusercontent.com/74904857/132223370-c43809ea-9839-450f-a470-0e82165910e6.png)

2021-09-06 15:16 UTC, minkyngkm commented
Thanks for your comments, @valentincanonical. 

The code snippet animation should work now! I set`$ docker pull ubuntu/nginx` as a default placeholder though just in case as you mentioned. Fixed the typo `mysq` as well. Hopefully it looks better! :)

2021-09-06 17:10 UTC, valentincanonical commented
Thanks @minkyngkm . I have one last comment, sorry I didn't make it earlier: Is it possible to add a line break after 'Long Term Supported' so that 'OCI Images' always is on the second line? That would make it much easier to parse for the readers' eyes. Thanks 🙏

![Screenshot 2021-09-06 at 19 10 07](https://user-images.githubusercontent.com/74904857/132247899-7b5ecef1-2346-4f8d-92cf-4a7fc23cc47b.png)

Once this is done: should I be the one to review the PR? Everything else looks good to me, I'd be happy to do it but I wonder if there's supposed to be a code review and that I shouldn't be the one to approve.

2021-09-06 18:13 UTC, anthonydillon requested changes
Looks great @minkyngkm. Few small suggestions in the code.

2021-09-06 18:13 UTC, anthonydillon commented on templates/security/docker-images.html
>        <h2 class="u-sv3">Critical CVE fixes in 24 hours</h2>
This spacing utility adds to much padding below the title.

2021-09-06 18:13 UTC, anthonydillon commented on templates/security/docker-images.html
> +      <li>Customer-only content with up to ten years of fixes. <a href="/security/contact-us?product=docker" class="js-invoke-modal">Contact Us</a>.</li>
This should be "Contact us"

2021-09-06 18:19 UTC, anthonydillon reviewed
Also should typer script go in the third-party directory in js folder?

2021-09-07 08:00 UTC, minkyngkm commented
> Also should typer script go in the third-party directory in js folder?

Thanks for reviewing @anthonydillon :) I moved it to the third-party directory 🙌

2021-09-07 08:52 UTC, minkyngkm commented on templates/security/docker-images.html
> +{% block title %}LTS Docker Images | Ubuntu{% endblock %}
Didn't know that! Thanks!! Fixed 👍

2021-09-07 10:13 UTC, minkyngkm commented
@anthonydillon Merging is blocked 🤔  Because it's not approved yet?

2021-09-07 10:20 UTC, anthonydillon approved these changes

2021-09-07 10:20 UTC, anthonydillon commented
Sorry, done.

2021-09-07 10:23 UTC, valentincanonical commented
@anthonydillon @minkyngkm just a note that I have replied on the copy doc if you want to turn the CTA texts into lowercase, that wasn't on purpose (as on the demo link I still see them capitalised).

2021-09-07 10:40 UTC, minkyngkm commented
> @anthonydillon @minkyngkm just a note that I have replied on the copy doc if you want to turn the CTA texts into lowercase, that wasn't on purpose (as on the demo link I still see them capitalised).

@valentincanonical Oh I didn't recognize the comments have been updated on the copy doc. Made it into lowercase :)

2021-09-07 10:50 UTC, merged