Make covered texts visible
canonical-web-and-design/ubuntu.com pull request #10335
Opened 2021-09-09 14:16 UTC by minkyngkm

## Done

- Updated margin to make covered texts visible 

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/cube
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Please check if any texts are covered by any images on small screens 

## Issue / Card

Fixes #10333 

## Screenshots

![image](https://user-images.githubusercontent.com/57550290/132702153-06e1da6e-440a-42ef-a032-cc1758fd6f3e.png)

2021-09-09 14:16 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10335.demos.haus

2021-09-10 08:16 UTC, bethcollins92 requested changes
This works as well, but to reduce the amount of inline styles we have the `u-sv3` class which you can add to the "Learn more about open badges" `<p>` tag which should also fix it

2021-09-10 08:23 UTC, minkyngkm commented
> This works as well, but to reduce the amount of inline styles we have the `u-sv3` class which you can add to the "Learn more about open badges" `<p>` tag which should also fix it

Thanks @bethcollins92 for reviewing! Oh yeah that seems better. Fixed! 👍

2021-09-10 08:24 UTC, bethcollins92 approved these changes
LGTM - thanks for updating 👍🏼

2021-09-10 08:25 UTC, merged