Gray out the logo and secondary nav
canonical-web-and-design/ubuntu.com pull request #10340
Opened 2021-09-10 14:03 UTC by minkyngkm

## Done

- Made Ubuntu logo and secondary nav grayed out when search bar is active 

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/ai
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

## Issue / Card

Fixes #9914 

## Screenshots

![image](https://user-images.githubusercontent.com/57550290/132865730-f6ecc617-3df0-4a27-a48a-b281f0a17d0e.png)

2021-09-10 14:03 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10340.demos.haus

2021-09-10 14:06 UTC, minkyngkm commented
@anthonydillon @anasereijo Should the global nav on the very top be grayed out? Because the navbar is from dependency @canonical/global-nav

2021-09-10 14:50 UTC, anthonydillon commented
This has affected the mega menu:
![image](https://user-images.githubusercontent.com/1413534/132873009-f2c62a89-be15-450e-afdf-22c3ee4b9efb.png)

2021-09-10 14:50 UTC, anthonydillon requested changes
QA issue

2021-09-10 14:53 UTC, anasereijo commented
> @anthonydillon @anasereijo Should the global nav at the very top be grayed out also? Because the navbar is from dependency @canonical/global-nav

Ideally yes, the global nav should also be grayed out, but I understand if it's not possible to do it or very complicated so willing to leave it like that.

2021-09-13 08:59 UTC, anthonydillon commented
Thanks @minkyngkm looking better. Found another issue. 
- Open and close the Product menu in the global nav
- Click search and you can see the content below the global nav
![image](https://user-images.githubusercontent.com/1413534/133055261-3af8ad61-616b-4a1b-af72-a9c268743419.png)

2021-09-13 11:04 UTC, minkyngkm commented
Thanks for QAing @anthonydillon  - Fixed that issue but I had to give some margins to the dropdown menu. When the search bar is active, the dropdown menu is open from the product button and then the screen gets smaller, the dropdown menu is not completely hidden because of the global nav bar's opacity. 
<img width="375" alt="Screenshot 2021-09-13 at 10 52 40 am" src="https://user-images.githubusercontent.com/57550290/133070793-1c06e7c0-c0b2-4146-b63a-5a7293e101e4.png">

It was a little bit tricky to update the styles because the global nav is from dependency. It looks okay for me but since the margin is added slightly, it might need some design review. Please let me know what you think :) 
![image](https://user-images.githubusercontent.com/57550290/133072682-41ac155b-e605-4232-8d7d-e8a9c5c27c37.png)

2021-09-13 11:52 UTC, anthonydillon commented
Thanks, that is working now but there is a missing overlay behind the mega menu:
![image](https://user-images.githubusercontent.com/1413534/133078726-b05ea4ae-25ae-4967-b067-dac6c08ba5d1.png)

2021-09-14 08:12 UTC, anthonydillon commented
Awesome work @minkyngkm this is looking great. One small (I hope last thing) is that when you open the download menu and click the content overlay it does not close the menu. Is that something you could look into please.

2021-09-15 11:43 UTC, minkyngkm commented
Hi @anthonydillon. Thanks for reviewing! :) I had to update the secondary menu(The red area in the screenshot below)'s z-index.
<img width="992" alt="Screenshot 2021-09-15 at 12 35 24 pm" src="https://user-images.githubusercontent.com/57550290/133426340-79ce4d59-df50-479f-8a91-41ff05f3e7b4.png">
It seems to be working fine but its grayed out a little bit later compared to other components because it just changes z-index. Would there be any better way to fix it other than changing z-indexes? Also, when the secondary menu is open and the search bar is active and then if you click the menu area, the menu is closed with the search bar because of the search bar's z-index I guess... Would that be okay?

2021-09-16 15:12 UTC, anthonydillon commented
@minkyngkm I see the styles added to the global nav are causing issues and its still clickable so I would suggest removing the global nav masking and leaving it clickable for now.

2021-09-17 08:25 UTC, minkyngkm commented
> @minkyngkm I see the styles added to the global nav are causing issues and its still clickable so I would suggest removing the global nav masking and leaving it clickable for now.

@anthonydillon Hi Ant! Thank you for reviewing 🙌. I fixed the global nav issue. It seems to be fixed - Could you please look once again and then I will remove it if it's still not working! Thank you again 🙏🏻

2021-09-17 12:39 UTC, anthonydillon requested changes

2021-09-17 12:39 UTC, anthonydillon commented on templates/templates/_navigation.html
> +    globalNav.style= "max-width:68rem; opacity: 0.4; transition: opacity 0.5s ease-in-out;"
Lets not do this as the expected place to set the max-width is the init script of the global nav. I think its better to leave it untouched and active when searching.

2021-09-17 13:11 UTC, minkyngkm commented
Thanks @anthonydillon for reviewing again. Made the global nav back as it was before. Hopefully it's all good now - [demo](https://ubuntu-com-10340.demos.haus)

2021-09-17 13:40 UTC, anthonydillon approved these changes
LGTM :+1: thanks for all the work here @minkyngkm

2021-09-17 14:47 UTC, merged