Update the content of /ceph to match the copy doc
canonical-web-and-design/ubuntu.com pull request #10400
Opened 2021-09-17 12:45 UTC by goulinkh

## Done

- Update the content of /ceph to match the copy doc

## QA

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4423

## Screenshots

![Screenshot from 2021-09-17 14-45-02](https://user-images.githubusercontent.com/36013798/133784564-b2d09516-59cd-44c1-a797-945ba8d611b3.png)

2021-09-17 12:45 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10400.demos.haus

2021-09-17 12:51 UTC, goulinkh commented
Waiting for design team to check that the new diagram is good

2021-09-20 09:06 UTC, mtruj013 requested changes
Hi @goulinkh! Looks good, just a couple of small changes:

2021-09-20 09:06 UTC, mtruj013 commented on templates/ceph/index.html
> +      <p><a class="p-link--external" href="/advantage">Find out more</a></p>
This isn't an external link so you can remove the `p-link--external` class

2021-09-20 09:06 UTC, mtruj013 commented on templates/ceph/index.html
> +      <p><a class="p-link--external" href="/ceph/install">Install Charmed Ceph</a></p>
Remove `p-link--external` class

2021-09-20 09:06 UTC, mtruj013 commented on templates/ceph/index.html
> +      <p><a class="p-link--external" href="/ceph/managed">Find out more</a></p>
Remove `p-link--external` class

2021-09-20 11:28 UTC, mtruj013 approved these changes
LGTM!

2021-09-20 13:45 UTC, goulinkh commented
@bethcollins92 I think the design team already approved the illustration: https://github.com/canonical-web-and-design/web-squad/issues/4424

2021-09-20 14:11 UTC, bethcollins92 commented
Nope - all is good, I just popped it on there as I saw your comment about waiting for design

2021-09-20 14:28 UTC, merged