WIP Observability build
canonical-web-and-design/ubuntu.com pull request #10439
Opened 2021-09-21 16:07 UTC by mtruj013

## Done
Building /observability/what-is-observability per copydoc: https://docs.google.com/document/d/1eoqDQzFiRJY2u_EO4JBuLBLqae4K3nrEf3qd88KHw0Y/edit

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4380

## Screenshots
![Screenshot 2021-09-21 at 18 03 39](https://user-images.githubusercontent.com/17607612/134206407-db101d87-8018-44ec-a7ff-1611701c759b.png)

![Screenshot 2021-09-21 at 18 03 59](https://user-images.githubusercontent.com/17607612/134206449-9ee30e37-d306-4ff4-a462-8e53744ed56e.png)
![Screenshot 2021-09-21 at 18 04 13](https://user-images.githubusercontent.com/17607612/134206490-85c8438b-8dea-4cac-b2e3-35e53053172a.png)

2021-09-21 16:07 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10439.demos.haus

2021-09-22 10:49 UTC, mmanciop commented
@pmahnke when this page goes live we need to fix the footer :-)
Now that the /observability section has more than one page, it can take its rightful place in the footer as section, I'd say above Appliances. WDYT?

2021-09-22 10:55 UTC, mmanciop requested changes
A couple minor changes are needed IMO (see comments), and there is additionally the need to change the footer, but as a first iteration, we are pretty much there :-)

2021-09-22 10:55 UTC, mmanciop commented on templates/observability/what-is-observability.html
> +                url="https://assets.ubuntu.com/v1/700713ff-telemetry-types.svg",
https://assets.ubuntu.com/v1/1101e891-telemetry_types.svg

2021-09-22 10:55 UTC, mmanciop commented on templates/observability/what-is-observability.html
> +    <div class="p-strip--suru-bottomed">
I like it *much* more with `p-strip--suru-topped` instead :-)

2021-09-22 11:33 UTC, mtruj013 commented
@mmanciop about to push those changes and open for review now,  but also what do you think about the colon here? I think a period would be more grammatically correct

> Observability is a crucial property of well-designed software systems: your system
> is observable if you can know whether it is working as desired and, if it is not, who
> is impacted and how badly, what the issues are and where they are originating
> from.

2021-09-22 13:40 UTC, mmanciop commented
> @mmanciop about to push those changes and open for review now, but also what do you think about the colon here? I think a period would be more grammatically correct
> 
> > Observability is a crucial property of well-designed software systems: your system
> > is observable if you can know whether it is working as desired and, if it is not, who
> > is impacted and how badly, what the issues are and where they are originating
> > from.

I'd be fine with that change, it is easier to read

2021-09-23 08:49 UTC, long-chung commented
- [ ] Suru strip in the header is in the wrong place
- [ ] Cross check spacing in the "Monitoring and telemetry types" Hard to see which sub head belongs to copy as spacing looks equal between paragraphs.
- [ ] Check the image ratio on "Telemetry correlation for deeper insights" section. Image looks like its squished in the x-axis

2021-09-23 09:46 UTC, mtruj013 commented
Hi @long-chung, regarding the suru strip header, @mmanciop mentioned that he preferred it on the top as opposed to the bottom (see comments above). You guys let me know what the final decision on that is and I'll go ahead and implement

2021-09-23 09:48 UTC, long-chung commented
@mtruj013 "mentioned that he preferred it on the top as opposed to the bottom" 
Coolies. Thats fine. Proceed with suru strip at the top then. Thanks

2021-09-23 14:53 UTC, mtruj013 commented
@long-chung Done! lmk if the spacing/ image look better or if they still need a touch up

2021-09-23 15:13 UTC, bethcollins92 commented on templates/observability/what-is-observability.html
> +            <h3 class="p-heading--4">Rather, observability <em>through</em> monitoring</h3>
not your fault but could you remove the italics please? Conversation [here](https://chat.canonical.com/canonical/pl/bqqyrj7b3ibwifat4eefit3zoh)

2021-09-23 15:13 UTC, bethcollins92 commented on templates/observability/what-is-observability.html
> +                    url="https://assets.ubuntu.com/v1/1101e891-telemetry_types.svg",
I'd hide this image on small screens it's hard to see what's going on on mobile

2021-09-23 15:32 UTC, long-chung commented
@mtruj013 Thanks for sorting out the spacing.

I'm still seeing stretching on the Telemetry image. If I view source, its currently rendering at 682x665px, Whereas the original source file is 683x595, so it's getting squashed by 70px on the horizontal axis.

2021-09-23 15:41 UTC, bethcollins92 approved these changes
Nice, LGTM - I'm sure it will look a lot better once all the illustrations are done and can be added

2021-09-24 10:58 UTC, merged