Replace "Canonical livepatch" with "Ubuntu livepatch"
canonical-web-and-design/ubuntu.com pull request #10495
Opened 2021-09-24 11:34 UTC by goulinkh

## Done

- Updated the page ubuntu.com/security/livepatch to match the [copy doc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit#)

## QA

- Go to the webiste  /security/livepatch
- Make sure that the content changes in the [copy doc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit#) are applied

## Issue / Card

Fixes #10486

2021-09-24 11:34 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10495.demos.haus

2021-09-27 13:27 UTC, mtruj013 requested changes
Hi @goulinkh! I believe this needs to be tackled as well

<img width="767" alt="Screenshot 2021-09-27 at 15 24 27" src="https://user-images.githubusercontent.com/17607612/134917574-ae0978d0-e663-48f4-93e8-9e61d71c920e.png">

2021-09-27 13:46 UTC, goulinkh commented
@mtruj013 Sorry I didn't notice the comment!

2021-09-28 07:41 UTC, mtruj013 approved these changes
LGTM!👍🏻

2021-09-29 08:06 UTC, merged