Removed the maintenance updates from the release cycle
canonical-web-and-design/ubuntu.com pull request #10512
Opened 2021-09-27 11:25 UTC by goulinkh

## Done

- Removed the maintenance updates from the release cycle in the page ubuntu.com/about/release-cycle as requested in the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#)

## QA

- Go to the website
- Make sure that the maintenance updates are removed as mentioned in the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#) and mark the discussion in the [doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#) as done

## Issue / Card

Fixes #10504

## Screenshots

### Before

![Screenshot from 2021-09-27 12-55-19](https://user-images.githubusercontent.com/36013798/134898377-10c21d90-6cf7-479f-8b9e-5bb10e90b307.png)

### After

![Screenshot from 2021-09-27 13-16-08](https://user-images.githubusercontent.com/36013798/134898395-bf53ee5a-2b7b-486e-88af-da0adbee04ed.png)

2021-09-27 11:25 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10512.demos.haus

2021-09-28 08:17 UTC, bethcollins92 requested changes
Could you remove the maintenance updates from the key please? 

<img width="953" alt="Screenshot 2021-09-28 at 09 17 14" src="https://user-images.githubusercontent.com/58959073/135050095-2d903953-3547-4378-98a6-7bec3cd4f446.png">

2021-09-28 13:42 UTC, bethcollins92 commented
@goulinkh Waiting for a response from @SirSamTumless about whether we need to include all the new copy changes from further down the page

2021-09-28 15:09 UTC, SirSamTumless commented
@bethcollins92, @goulinkh confirmed it is just the chart that needs changing!

2021-09-29 07:55 UTC, bethcollins92 approved these changes
LGTM 👍🏼

2021-09-29 08:07 UTC, merged