Microcerts fix data inconsistencies across environments
canonical-web-and-design/ubuntu.com pull request #10831
Opened 2021-11-09 19:54 UTC by carkod

## Done

- [List of work items including drive-bys - remember to add the why and what of this work.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

2021-11-09 19:55 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10831.demos.haus

2021-11-22 14:05 UTC, mrgnr requested changes
Environment switching isn't working properly because `test_backend` is used in some places where we need `is_test_backend`.

2021-11-22 14:05 UTC, mrgnr commented on webapp/advantage/decorators.py
> +                BADGR_ISSUER if not test_backend else QA_BADGR_ISSUER
Should be `is_test_backend`

2021-11-22 14:05 UTC, mrgnr commented on webapp/advantage/decorators.py
> +                CERTIFIED_BADGE if not test_backend else QA_CERTIFIED_BADGE,
Should be `is_test_backend`

2021-11-22 14:05 UTC, mrgnr commented on webapp/advantage/decorators.py
> +                if not test_backend
Should be `is_test_backend`

2021-11-22 14:05 UTC, mrgnr commented on webapp/advantage/decorators.py
> +                if not test_backend
Should be `is_test_backend`

2021-11-22 14:05 UTC, mrgnr commented on webapp/advantage/decorators.py
> +                if not test_backend
Should be `is_test_backend`

2021-11-22 14:05 UTC, mrgnr commented on webapp/advantage/decorators.py
> +                if not test_backend
Should be `is_test_backend`

2021-11-22 14:05 UTC, mrgnr commented on webapp/advantage/decorators.py
> +                if not test_backend
Should be `is_test_backend`

2021-11-22 14:12 UTC, jpmartinspt commented on webapp/cube/api.py
> +        print("Over here")
Remove prints

2021-11-22 15:28 UTC, jpmartinspt approved these changes

2021-11-22 16:02 UTC, merged