Removed mid sections and updated remaining copy
canonical-web-and-design/ubuntu.com pull request #10883
Opened 2021-11-17 15:41 UTC by mtruj013

## Done

- Updated as per [copy doc](https://docs.google.com/document/d/1NxJdT3BD6EWnpsu-eathNyranQVImnDGhuCjzsIWh4s/edit#heading=h.olm94bbyu9dm)

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
**NOTE: PAGE MUST BE MERGED IN CONJUNCTION WITH [NEW PAGE](https://github.com/canonical-web-and-design/ubuntu.com/pull/10862)**

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4580

2021-11-17 15:41 UTC, webteam-app commented
Demo starting at https://ubuntu-com-10883.demos.haus

2021-11-18 13:00 UTC, mmanciop requested changes

2021-11-18 13:00 UTC, mmanciop commented on templates/observability/index.html
>          <a class="p-button--positive js-invoke-modal" href="/observability/contact-us">
Should go to /observability/managed

2021-11-19 13:10 UTC, petesfrench approved these changes
LGTM :+1: have you seen Micheal's comment?

2021-11-19 13:36 UTC, mtruj013 commented
> LGTM 👍 have you seen Micheal's comment?

Yup! Just waiting on the other pr to be merged so I can link it

2021-11-23 14:47 UTC, petesfrench approved these changes

2021-11-23 14:51 UTC, merged