Build /iot-management page
canonical-web-and-design/ubuntu.com pull request #11020
Opened 2021-12-09 11:58 UTC by minkyngkm

## Done

- Build `/internet-of-things/iot-management` page

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Be sure to test on mobile, tablet and desktop screen sizes
- Please check page against [copy doc(https://docs.google.com/document/d/1C-1ywVzBHkc4I3f-G7Rpy-epaXdbPisbolHUC1Jb7cE/edit#) 
- Please refer to this [brief](https://docs.google.com/document/d/1ENKan1AIRTkzdARyYYE6U9lW1jhw5sRVY76GKrRRa2Y/edit) and [doc](https://docs.google.com/document/d/1Se-fD5hhb7EaR75jd_1D-JkADmg6aLjUs7_bScATvwE/edit#) for contact form 
## Issue / Card

Fixes [#4671](https://github.com/canonical-web-and-design/web-squad/issues/4671)

## Screenshots

<img width="1440" alt="IoT Management - Manage Ubuntu Core devices | Ubuntu (2021-12-09 11-56-43)" src="https://user-images.githubusercontent.com/57550290/145392358-6ab2667b-d786-4e81-ad25-11cd17e509e8.png">

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

2021-12-09 11:58 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11020.demos.haus

2021-12-09 16:09 UTC, spencerbygraves commented
Thanks @minkyngkm looks good 👍

2021-12-10 09:50 UTC, sowasred2012 requested changes
Looking good - just two small changes. We should ping marketing (David or Lucia) about a form ID too.

2021-12-10 09:50 UTC, sowasred2012 commented on templates/internet-of-things/iot-management.html
> +      <p><a class="p-link--inverted"href="/iot-device-management-whitepaper?_ga=2.90790234.1537229770.1638375570-1154790289.1626446765">Secure IoT device management&nbsp;&rsaquo;</a></p>
```suggestion
      <p><a class="p-link--inverted"href="/engage/iot-device-management-whitepaper?_ga=2.90790234.1537229770.1638375570-1154790289.1626446765">Secure IoT device management&nbsp;&rsaquo;</a></p>
```

2021-12-10 09:50 UTC, sowasred2012 commented on templates/internet-of-things/iot-management.html
> +      <p><a class="p-link--inverted p-link--external"href="/engage/smart-start-whitepaper">Accelerating IoT device time to market&nbsp;&rsaquo;</a></p>
```suggestion
      <p><a class="p-link--inverted" href="/engage/smart-start-whitepaper">Accelerating IoT device time to market&nbsp;&rsaquo;</a></p>
```

2021-12-10 10:09 UTC, sowasred2012 commented on navigation.yaml
> +      path: /internet-of-things/iot-management
```suggestion
      path: /internet-of-things/management
```

2021-12-10 12:09 UTC, sowasred2012 approved these changes
LGTM - just need that form ID before it gets merged

2021-12-14 11:54 UTC, merged