Update further reading on /managed/apps/cassandra
canonical-web-and-design/ubuntu.com pull request #11035
Opened 2021-12-13 10:07 UTC by minkyngkm

## Done

- Update further reading on `/managed/apps/cassandra`

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/apps/cassandra
- Be sure to test on mobile, tablet and desktop screen sizes
- Please check page against [copy doc](https://docs.google.com/document/d/1iYMH1ISY4uDtr3ZzH0f_hnEzvqaeufO43z__cMxs0vQ/edit#) and resolve comments

## Issue / Card

Fixes [#4696](https://github.com/canonical-web-and-design/web-squad/issues/4696)

## Screenshots

![image](https://user-images.githubusercontent.com/57550290/145792381-5d4e1496-ab2b-42ae-bffa-bf48de5fc174.png)

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

2021-12-14 12:01 UTC, anthonydillon requested changes
Code looks ok but I don't see this section in the attached copy doc.

2021-12-14 12:14 UTC, minkyngkm commented
> Code looks ok but I don't see this section in the attached copy doc.

Thanks @anthonydillon for reviewing! - there seems to be a comment made by the PM for this section on the copy doc. could you please take a look again? [copy doc](https://docs.google.com/document/d/1iYMH1ISY4uDtr3ZzH0f_hnEzvqaeufO43z__cMxs0vQ/edit#)

2021-12-15 11:47 UTC, anthonydillon commented
Ah ok :+1:

2021-12-15 18:40 UTC, anthonydillon approved these changes

2021-12-16 09:00 UTC, merged