Added Screenly section
canonical-web-and-design/ubuntu.com pull request #11058
Opened 2021-12-15 19:02 UTC by mtruj013

## Done

- Updated page as per [copy doc](https://docs.google.com/document/d/1mXnYnpaCJznDLtYn9Q74aVeEI3iFxVOMzF0pdL7wdu0/edit)

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4724

## Screenshots 
<img width="1001" alt="Screenshot 2021-12-15 at 14 01 26" src="https://user-images.githubusercontent.com/17607612/146248658-72968178-8876-4f45-930a-5b66c69b62c3.png">

2021-12-15 19:02 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11058.demos.haus

2021-12-15 19:13 UTC, anthonydillon commented
@mtruj013 the QA steps here could be better.

2021-12-15 19:36 UTC, mtruj013 commented
> @mtruj013 the QA steps here could be better.

Yup, I noticed one more thing I had to fix after I made the PR, meant to tackle that first and then come back and finish the QA steps. They're updated now :)

2021-12-15 21:39 UTC, anthonydillon requested changes
Code looks good but the new separator is outside of a strip adding to much padding.

2021-12-15 21:39 UTC, anthonydillon commented on templates/core/stories.html
> +</div>
The spacing would look better here if this was within the same strip. I would wrap all of this together like the separator below

2021-12-17 10:52 UTC, anthonydillon approved these changes

2021-12-17 10:56 UTC, merged