Rebuild page on /certified
canonical-web-and-design/ubuntu.com pull request #11118
Opened 2022-01-06 15:07 UTC by minkyngkm

**BLOCKED:** The`certified/why-certifed` page ([issue](https://github.com/canonical-web-and-design/web-squad/issues/4728)) needs to be merged first 

## Done

- Rebuild page on /certified
- The image in the last section needs to be updated. 

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/certified
    - Be sure to test on mobile, tablet and desktop screen sizes
- Please check page against [copy doc](https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit#) 

## Issue / Card

Fixes [#4697](https://github.com/canonical-web-and-design/web-squad/issues/4697)

## Screenshots

<img width="1440" alt="Certified hardware | Ubuntu ()" src="https://user-images.githubusercontent.com/57550290/148403443-449241cb-e495-4dd9-aba7-ccea502e0eb1.png">

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

2022-01-06 15:07 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11118.demos.haus

2022-01-11 14:25 UTC, davegoddard42 commented
LGTM @minkyngkm. Nice work!

2022-01-13 10:11 UTC, sowasred2012 requested changes
The copy doc has a few big differences, not sure if I'm looking at an old version? https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit#heading=h.3ziq16wcvhzr

2022-01-13 10:11 UTC, sowasred2012 commented on templates/certified/index.html
> +      <p>Many of the world's biggest PC manufacturers certify their desktops for Ubuntu, ensuring it always runs as smoothly as its millions of users expect. Ubuntu is fast, reliable, packed with gre
This is different in the copy doc:
```suggestion
      <p>Many of the world's biggest PC manufacturers certify their desktops for Ubuntu, ensuring these systems always run as smoothly as their millions of users expect. Ubuntu is fast, reliable, packed with great software, and free of viruses. That’s why you’ll find Ubuntu preloaded on desktops across government, education, enterprise, and in homes around the world..</p>
```

2022-01-13 10:11 UTC, sowasred2012 commented on templates/certified/index.html
> +      <h2>Ubuntu certified SoCs</h2>
```suggestion
      <h2>Ubuntu Certified SoCs</h2>
```

2022-01-13 10:11 UTC, sowasred2012 commented on templates/certified/index.html
> +      <p>Low-power small-footprint System on a Chip (SoC) hardware are re-defining the future of sustainable data centers. Ubuntu Core delivers bullet-proof security, reliable updates and access to a
```suggestion
      <p>64-bit ARM based System on a Chip (SoC) hardware is re-defining the future of sustainable data centers. Featuring high core counts and lower power consumption and cooling needs, Ubuntu Certified Servers that utilize certified System on Chip hardware can lower your costs while allowing you to scale up and out to meet customer demand.</p>
```

2022-01-13 10:11 UTC, sowasred2012 commented on templates/certified/index.html
>        <p>Canonical's certification program offers server manufacturers a selection of SoCs officially supported and maintained in Ubuntu to choose from for their products from servers to IoT.</p>
```suggestion
      <p>Canonical's certification program offers server manufacturers a selection of SoCs officially supported and maintained in Ubuntu to choose from for their products.</p>
```

2022-01-13 10:55 UTC, davegoddard42 commented
Apologies, this is my fault - I should've picked up during review. The copy doc has the correct text - I focused on the visual design when I reviewed the demo webpage, I didn't spot the copy hadn't been updated.

2022-01-13 11:07 UTC, minkyngkm commented
@davegoddard42 no worries!  @sowasred2012 I have made some updates. Thanks all :)

2022-01-13 11:44 UTC, sowasred2012 approved these changes
LGTM - thanks!

2022-01-13 12:10 UTC, merged