Copy update on /security/disa-stig
canonical-web-and-design/ubuntu.com pull request #11112
Opened 2022-01-05 13:09 UTC by minkyngkm

## Done

- Copy update on `/security/disa-stig`

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/disa-stig
    - Be sure to test on mobile, tablet and desktop screen sizes
- Please check page against [copy doc](https://docs.google.com/document/d/1zJwZzc-cERj9YKNXFtmrXwynJptyT7-D3qCNzBctRfo/edit#) and resolve comments

## Issue / Card

Fixes [#4739](https://github.com/canonical-web-and-design/web-squad/issues/4739)

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

2022-01-05 13:09 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11112.demos.haus

2022-01-05 14:46 UTC, anthonydillon requested changes
LGTM :+1: with a small change to the page title and some suggestions in the copy doc for the page author.

2022-01-06 09:07 UTC, minkyngkm commented
Thanks @anthonydillon for reviewing. I've made some changes :)

2022-01-06 10:37 UTC, anthonydillon approved these changes
LGTM :+1:

2022-01-13 16:12 UTC, nmav commented on templates/security/disa-stig.html
> +              <pre class="p-code-snippet__block--icon"><code>sudo usg fix stig</code></pre>
can we change this to `disa_stig`?
The tooling changed since the page creation. I've updated the copydoc already

2022-01-13 16:19 UTC, minkyngkm commented
@nmav It's been just updated :)

2022-01-14 08:51 UTC, nmav commented
Thank you!

2022-01-14 08:59 UTC, minkyngkm commented
@nmav is this page https://ubuntu.com/security/certification/docs/disa-stig going to be ready today(14th)?

2022-01-14 09:42 UTC, nmav commented
Thank you!

> @nmav is this page https://ubuntu.com/security/certification/docs/disa-stig going to be ready today(14th)?

Right. I've replied on mm as well, but for the record, let's get it live at 15.00 CET

2022-01-14 13:37 UTC, nmav commented
@minkyngkm what I noticed is that the preview of the video is different than the same preview at https://ubuntu.com/security/fips

could we make it consistent as the other one?

2022-01-14 13:38 UTC, nmav commented
![Screenshot from 2022-01-14 14-38-43](https://user-images.githubusercontent.com/1745073/149524200-01847935-3d7b-41d5-ad22-6501f885fb71.png)
![Screenshot from 2022-01-14 14-38-33](https://user-images.githubusercontent.com/1745073/149524205-a0e58cec-ac8f-43af-9c19-2a76be5e1e3b.png)

2022-01-14 15:00 UTC, nmav approved these changes

2022-01-14 15:03 UTC, merged