Build openstack-cheat-sheet page
canonical-web-and-design/ubuntu.com pull request #11175
Opened 2022-01-21 14:51 UTC by minkyngkm

## Done

- Build page on `/openstack/openstack-cheat-sheet`

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/openstack-cheat-sheet
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

2022-01-21 15:29 UTC, anthonydillon requested changes
Free comments in the code but mostly the based on the copy

2022-01-21 15:29 UTC, anthonydillon commented on templates/openstack/openstack-cheat-sheet.html
> +      <p> What’s included:</p>
Can you straighten this quote please.

2022-01-21 15:29 UTC, anthonydillon commented on templates/openstack/openstack-cheat-sheet.html
> +      <a href="https://assets.ubuntu.com/v1/8d3130a1-OpenStack.cheat.sheet.1.pdf?_ga=2.38929315.1481755299.1641543595-1851044449.1622191471" class="p-button--positive">Get OpenStack cheat sheet</a>
This is not good English.
```suggestion
      <a href="https://assets.ubuntu.com/v1/8d3130a1-OpenStack.cheat.sheet.1.pdf?_ga=2.38929315.1481755299.1641543595-1851044449.1622191471" class="p-button--positive">Get the OpenStack cheat sheet</a>
```

2022-01-21 15:29 UTC, anthonydillon commented on templates/openstack/openstack-cheat-sheet.html
> +      <h1>OpenStack Cheat Sheet</h1>
This is not a name.
```suggestion
      <h1>OpenStack cheat sheet</h1>
```

2022-01-21 16:34 UTC, minkyngkm commented
Thanks @anthonydillon for reviewing! (It was actually WIP earlier) Hopefully it looks better now :)

2022-01-21 16:42 UTC, minkyngkm commented
Hi @spencerbygraves! Could you please take a look at this page for a design review when you have time? :)

2022-01-21 16:49 UTC, anthonydillon requested changes
You should add this new page to the navigation of the site so the user doesn't lose there way

2022-01-21 17:05 UTC, anthonydillon requested changes
Should the button be full width? 
![image](https://user-images.githubusercontent.com/1413534/150569428-4beabc6b-ee47-49f9-896d-3f070c172402.png)

2022-01-21 22:23 UTC, anthonydillon commented on navigation.yaml
> +    - title: OpenStack Cheat sheet
```suggestion
    - title: OpenStack cheat sheet
```

2022-01-24 08:32 UTC, minkyngkm commented
Thanks @anthonydillon for reviewing! I've made changes and also just moved the CTA to the left. 
One question - I was just wondering if it's better for the title of this page and url to be just "Cheat sheet" without "OpenStack" in the navigation. 
![image](https://user-images.githubusercontent.com/57550290/150747034-e46d30fa-567f-4a98-acbe-bed8ca497ef6.png)

2022-01-24 09:30 UTC, minkyngkm commented
The navigation title and url have been updated from "OpenStack cheat sheet to "Cheat sheet" 
![image](https://user-images.githubusercontent.com/57550290/150756629-6ca9cff7-e51c-444f-8c61-e77596e1d885.png)

2022-01-24 09:33 UTC, pmahnke commented
@minkyngkm @davegoddard42 @sowasred2012 I have pinged marketing.  I find this page very strange on its own, not as a strip on another page. Please don't publish yet.

2022-01-26 09:38 UTC, pmahnke commented
@minkyngkm I have a response:

> Hi @Peter Agree with your suggestion of having a strip on tutorials and what is openstack pages (+hidden in the menu for ranking purposes)

2022-01-27 09:29 UTC, pmahnke commented
@minkyngkm I updated the /[tutorials](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit#) and /[what-is-openstack](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#) pages.  

The strip can be an include as they are the same.

Please hide the cheat sheet page from the navigation.

You might want to revert its name back to /openstack-cheat-sheet for SEO.

2022-01-27 13:55 UTC, minkyngkm commented
Thanks @pmahnke! I have made some updates.

2022-01-27 16:44 UTC, spencerbygraves commented
@minkyngkm I think you could make the subheading h4, but otherwise it looks good.

Thanks.

2022-01-27 16:52 UTC, minkyngkm commented
Thanks @spencerbygraves for your feedback! Its been updated! :)

![image](https://user-images.githubusercontent.com/57550290/151405524-165c7d0a-1f9d-4924-822a-166a001a05a7.png)

2022-01-28 09:39 UTC, cristinadresch commented
@pmahnke could you rereview this one please, thanks

2022-01-28 10:13 UTC, pmahnke approved these changes
+1, I think it looks good.

2022-01-28 11:37 UTC, merged