Refresh managed apps
canonical-web-and-design/ubuntu.com pull request #11243
Opened 2022-02-11 12:20 UTC by grobbie

## Done

- Removed some out of date listings
- Replaced a listing

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

APPSPM-85

## Screenshots

2022-02-11 12:20 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11243.demos.haus

2022-02-11 13:06 UTC, anthonydillon requested changes
Done small a11y improvements

2022-02-11 13:06 UTC, anthonydillon commented on templates/managed/apps/index.html
> +            <p class="p-muted-heading">LOW LATENCY QUERIES FOR BIG DATA</p>
Could you sentence case this for better screen reader accessibility?

2022-02-11 13:06 UTC, anthonydillon commented on templates/managed/apps/index.html
> +            <p class="p-muted-heading" style="margin-left: 1rem">AI/MLOPS AT ANY SCALE</p>
Same here, please

2022-02-11 13:06 UTC, anthonydillon commented on templates/managed/apps/index.html
> +            <p class="p-muted-heading">THE WEBSCALE DATABASE</p>
Same here please

2022-02-11 13:08 UTC, anthonydillon reviewed
Could you please update the copy doc for this page please.
https://docs.google.com/document/u/1/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/mobilebasic

2022-02-11 15:01 UTC, grobbie commented
Updated for a11y and updated the copy doc [here](https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit) - please check there isn't a duplicate

2022-02-16 10:11 UTC, sowasred2012 requested changes
Looks good, just two bits of housekeeping.

2022-02-16 10:11 UTC, sowasred2012 commented on templates/managed/apps/index.html
>            attrs={"style": "height: 80px; width: auto;"},
The image is rendering in a way that makes it look low res, this fixes it:
```suggestion
          alt="OpenSearch",
          width="200",
          height="40",
          hi_def=True,
          loading="lazy",
          attrs={"style": "margin-top:.8rem;"},
```

2022-02-16 10:11 UTC, sowasred2012 commented on templates/managed/apps/index.html
>          <div style="min-width: 50%">
This "MongoDB CE" block looks odd without an image compared to the others, almost as if the image failed to load and the alt text is being display instead. Is there nothing we could use? If not, we could align it a little better with:

```suggestion
        <div style="min-width: 50%; margin-top: 2.4rem; margin-bottom: 2rem;">
```

2022-02-16 11:04 UTC, sowasred2012 approved these changes
LGTM

2022-02-16 11:06 UTC, merged