Reintroduce beta notification
canonical-web-and-design/ubuntu.com pull request #11414
Opened 2022-03-29 14:08 UTC by ClementChaumel

## Done

- Added the prompt to sign up for the beta programme back
- Added e2e tests checking for this message
- updated the notification to use the new action pattern

## QA

- go to /advantage
- see the notification
- log in
- see that the notification is still here

## Issue / Card

Fixes #11413

## Screenshots
![image](https://user-images.githubusercontent.com/11927929/160630164-b6490fac-49f6-4949-bc60-88602c0f3eb7.png)

2022-03-29 14:08 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11414.demos.haus

2022-03-30 11:40 UTC, sowasred2012 requested changes
@ClementChaumel looks good according to QA steps, but when I click the link to open the contact form modal, I can't close it by clicking the "X" (pressing Escape works though)

2022-03-30 15:44 UTC, ClementChaumel commented
> @ClementChaumel looks good according to QA steps, but when I click the link to open the contact form modal, I can't close it by clicking the "X" (pressing Escape works though)

Thanks, I fixed it. PTAL!

2022-03-30 16:05 UTC, sowasred2012 approved these changes
![noice](https://user-images.githubusercontent.com/2376968/160880269-74ea25a8-11b3-4847-aa8a-7242c701b49d.gif)

2022-03-30 16:28 UTC, merged