Refresh /desktop/developers page
canonical-web-and-design/ubuntu.com pull request #11493
Opened 2022-04-19 13:57 UTC by petesfrench

## Done

**Note: Waiting on 22.04 screenshots**

- Updates  /desktop/developers page for the 22.04 refresh, see [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)

## QA

- Go to /desktop/developers and compare against [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4960

2022-04-19 13:57 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11493.demos.haus

2022-04-19 14:16 UTC, local-optimum commented
Feedback (wrong copydoc btw, right one is linked here https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)
- Both laptop images needs updating, particularly the second one which is very out of date.
- The graph on what developers prefer should be next to the 'in good company' text section
- Would be good to have the Landscape icon in the landscape section
- Would be good to add the Rust logo to the 'tools' image

2022-04-19 15:31 UTC, mtruj013 requested changes
Looks good @petesfrench! Just a few comments, the majority of which are about wrapping dashes so nothing major. Also, TIL that "artifacts" is spelled "artefacts" in the UK 😅

2022-04-19 15:31 UTC, mtruj013 commented on templates/desktop/developers.html
> +      <h2>With Ubuntu, you're in good company</h2>
Is this supposed to be on the same section as the image above?

2022-04-20 10:24 UTC, petesfrench commented on templates/desktop/developers.html
> +  <section class="p-strip">
You are correct but the combination of tutorials isn't currently possible so I just did it manually for now

2022-04-20 11:18 UTC, anthonydillon requested changes
Few comments in the code

2022-04-20 11:18 UTC, anthonydillon commented on templates/desktop/developers.html
> +        <p>Whether you're an app or web developer, engineering manager, data scientist, or AI/ML researcher&mdash;Ubuntu is  your ideal workstation.</p>
```suggestion
        <p>Whether you're an app or web developer, engineering manager, data scientist, or AI/ML researcher &mdash; Ubuntu is your ideal workstation.</p>
```

2022-04-20 11:18 UTC, anthonydillon commented on templates/desktop/developers.html
> +            attrs={"class": "col-6 u-vertically-center u-hide--medium u-hide--small u-align--center"},
These classes are on the parent not the image

2022-04-20 11:18 UTC, anthonydillon commented on templates/desktop/developers.html
> +        <li class="p-list__item is-ticked">Has all the most popular productivity apps such as Slack, Microsoft Teams, Telegram, and Discord, available in the Snap Store</li>
Missing Zoom

2022-04-20 11:18 UTC, anthonydillon commented on templates/desktop/developers.html
> +            <li>Significant improvements for AMD and NVidia</li>
```suggestion
            <li>Significant improvements for AMD and NVIDIA</li>
```

2022-04-20 11:20 UTC, anthonydillon commented on templates/desktop/developers.html
>          <h2>Deployment made easy</h2>
This image could probably be hidden on small screens.

2022-04-20 11:41 UTC, anthonydillon approved these changes
Thanks LGTM :+1:

2022-04-20 11:42 UTC, merged