Copy update on /telco/osm
canonical-web-and-design/ubuntu.com pull request #11611
Opened 2022-05-16 09:53 UTC by minkyngkm

## Done

- Copy update on `/telco/osm`

## QA

- go to `/telco/osm`

## Issue / Card

Fixes [#5323](https://github.com/canonical-web-and-design/web-squad/issues/5323)

2022-05-16 09:53 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11611.demos.haus

2022-05-16 12:11 UTC, mtruj013 requested changes
Looks good @minkyngkm! Just a few comments in the code and this logo section needs a spacing fix for that last logo
![Screenshot 2022-05-16 at 14 06 19](https://user-images.githubusercontent.com/17607612/168589516-1a63c355-fd9b-439c-88f7-58650feaa91e.png)

2022-05-16 12:11 UTC, mtruj013 commented on templates/telco/osm/index.html
> +    <p>Follow the <a href="https://www.youtube.com/watch?v=DJhtjnWdfi8">video</a> of installation or <a href="https://juju.is/tutorials/charmed-osm-get-started#1-introduction">tutorial</a>. If you wi
The wording here is a little weird. "Follow the video of installation..." isn't technically grammatically incorrect as far as I know, but "Follow the installation video..." sounds a lot better I think. Also, "hands on" is an adjective so the sentence `If you wish to understand the whole architecture before hands on please watch this video` should be something like `If you wish to understand the whole architecture before getting hands on experience please watch this video.` I'll leave comments in the doc

2022-05-17 07:27 UTC, minkyngkm commented
Thanks @mtruj013 for reviewing! It's been all updated! 👍

2022-05-17 14:56 UTC, mtruj013 approved these changes
LGTM! Just a couple of minor things I missed:

2022-05-17 14:56 UTC, mtruj013 commented on templates/telco/osm/index.html
> +        <a href="/legal/ubuntu-advantage-service-description">Community Support&nbsp;&rsaquo;</a>
```suggestion
        <a href="https://osm.etsi.org/news-events/blog/72-etsi-osm-ten-declared-as-the-first-lts-version-of-open-source-mano">Community Support&nbsp;&rsaquo;</a>
```

2022-05-17 14:56 UTC, mtruj013 commented on templates/telco/osm/index.html
> +    <p>We also provide installation of <a href="https://www.youtube.com/watch?v=5iURQB8cLJ0">OSM in a box</a> with the minimum possible resources needed to be perfectly fucntional.</p>
```suggestion
    <p>We also provide installation of <a href="https://www.youtube.com/watch?v=5iURQB8cLJ0">OSM in a box</a> with the minimum possible resources needed to be perfectly functional.</p>
```

2022-05-18 06:49 UTC, merged