Update /download/iot with new section and link tags
canonical-web-and-design/ubuntu.com pull request #11678
Opened 2022-06-03 16:03 UTC by petesfrench

## Done

- Update /download/iot with new section and link tags

## QA

- Go to and compare against [copydoc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#heading=h.rcu78t62sv8b)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/5423

2022-06-03 16:03 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11678.demos.haus

2022-06-03 16:05 UTC, petesfrench commented
@spencerbygraves There is a request in the [copydoc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#heading=h.rcu78t62sv8b) to have a different background colour on the section 'Ubuntu Core 22 Beta is now available'. But I am not sure how that will work with the current flow of the page, any suggestions?

2022-06-06 11:14 UTC, spencerbygraves commented
@petesfrench perhaps you could try splitting that section into 2 strips, and trying `p-strip--suru` on the beta one.

2022-06-07 19:13 UTC, petesfrench commented
Thank you @spencerbygraves !

2022-06-14 07:46 UTC, mtruj013 requested changes
Looks good @petesfrench! There's been a change on the doc that needs addressing and also there's a spacing bug on line 32

2022-06-14 07:46 UTC, mtruj013 commented on templates/download/iot/index.html
> +        <p><a href="https://ubuntu.com/certified" class="p-button">Browse the full list of certified hardware</a></p>
David made a change on the copy doc and seems to want this button above the paragraph which is not our usual convention. Maybe that's a design or ux issue? He also changed the text to "The ultimate Ubuntu Experience: Get Certified Hardware"

2022-06-14 10:57 UTC, petesfrench commented
Closing as this is being completed in another [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/11699)

2022-06-14 10:57 UTC, closed without merging