WIP - refrseh core page
canonical-web-and-design/ubuntu.com pull request #11703
Opened 2022-06-13 11:12 UTC by minkyngkm

## Done

- [List of work items including drive-bys - remember to add the why and what of this work.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.html)

2022-06-13 11:12 UTC, webteam-app commented
Demo starting at https://ubuntu-com-11703.demos.haus

2022-06-13 15:23 UTC, davegoddard42 commented
@minkyngkm - quick update:

2. Follow this design for the cards please:

B. Use this icon for OTA update control please :)

https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_400,h_400/https://assets.ubuntu.com/v1/a43d61ae-update+control.svg

2022-06-13 16:13 UTC, minkyngkm commented
Thanks @davegoddard42 for your reviews and suggestions! Hopefully the page looks better!

I also updated this section. (Move the title to the white section) Does it look better now? 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/57550290/173397640-114be3e9-b840-455c-9729-f09b24918282.png">

2022-06-13 18:12 UTC, davegoddard42 commented
LGTM @minkyngkm. Nice work!

2022-06-14 14:34 UTC, sowasred2012 requested changes
Nice work, it's almost there, but the code needs some tidying up, and there's a couple of things that need fixing.

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +          <script>
This should either be at the end of the file, or in its own JS file - HTML and JS should be separate as much as possible, it's a lot easier to find and reason about JS when it is.

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +              var logo = partners_logo[randomNum]
`const` and `let` are being used in this script, so I think this `var` could be a `const` for consistency.

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +  <div class="row u-equal-height u-align--center u-vertically-center">
The links in this section don't line up with each other:
![image](https://user-images.githubusercontent.com/2376968/173599510-e6865aab-7159-495b-987b-785d5be7aa99.png)

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +      <h2 class="u-sv3">Get to market fast with our strong ecosystem</h2>
The copy doc has:

> Get to market fast with the strong ecosystem of our device partners and certified hardware

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +          <p class="p-media-object__content">Your power supply may not be reliable. Your devices will be. Resilience to adversity saves money and reputations.Rely on Ubuntu Core to deliver your softw
```suggestion
          <p class="p-media-object__content">Your power supply may not be reliable. Your devices will be. Resilience to adversity saves money and reputations. Rely on Ubuntu Core to deliver your software updates safely.</p>
```

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +        url="https://assets.ubuntu.com/v1/3db02edd-enterprise+management+.svg",
This image is different in the copy doc

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +<section class='p-strip--image p-banner-core' id="developers-love-ubuntu">
```suggestion
<section class="p-strip--light" id="developers-love-ubuntu">
```

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +<section class='p-strip' style="padding-bottom: 150px;">
```suggestion
<section class="p-strip" style="padding-bottom: 150px;">
```

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +      <p class='p-heading--5'>Bring apps from Ubuntu Server to Ubuntu Core</p>
```suggestion
      <p class="p-heading--5">Bring apps from Ubuntu Server to Ubuntu Core</p>
```

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +      <p class='p-heading--5'>From GitHub to Ubuntu Core in minutes.</p>
```suggestion
      <p class="p-heading--5">From GitHub to Ubuntu Core in minutes.</p>
```

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +<section class='p-strip--image p-banner-core is-deep' id="built-for-business">
```suggestion
<section class="p-strip--kight is-deep" id="built-for-business">
```

2022-06-14 14:34 UTC, sowasred2012 commented on templates/core/index.html
> +  <div class='row u-vertically-center'>
There's a lot of instances of single quotes used for attribute values - we should stick with double quotes for consistency and code cleanliness.

```suggestion
  <div class="row u-vertically-center">
```

2022-06-14 16:36 UTC, minkyngkm commented on templates/core/index.html
> +          <div class="p-logo-section__item"> <img src="https://assets.ubuntu.com/v1/8fdc3ebf-raspberry-pi-logo.png" class="p-logo-section__logo" style="max-height:120px; padding:10px" /> </div>
I set `max-height` and `padding` because all the logo sizes looked too different. I removed it now! Hopefully it looks better now!

2022-06-14 16:42 UTC, minkyngkm commented
Thanks @sowasred2012 for reviewing! I've made some changes. Hope it looks better now!

2022-06-15 11:06 UTC, sowasred2012 approved these changes
LGTM!

2022-06-15 11:09 UTC, merged