Update K8s release chart
canonical-web-and-design/ubuntu.com pull request #8196
Opened 2020-08-31 16:07 UTC by evilnick

## Done

The delayed release of Kubernetes 1.19 has a knock-on effect for the support chart on https://ubuntu.com/about/release-cycle
This fixes the dates on that chart

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

2020-08-31 16:08 UTC, webteam-app commented
Demo starting at https://ubuntu-com-8196.demos.haus

2020-08-31 19:16 UTC, anthonydillon requested changes
Looks like you typoed one of the dates.

2020-08-31 19:16 UTC, anthonydillon commented on templates/about/release-cycle.html
> +              <td align='right'>Feb 2020</td>
```suggestion
              <td align='right'>Feb 2021</td>
```

2020-09-01 10:49 UTC, evilnick commented on templates/about/release-cycle.html
> +              <td align='right'>Feb 2020</td>
I did, thanks!

2020-09-01 17:19 UTC, anthonydillon approved these changes
LGTM

2020-09-01 17:19 UTC, merged