WIP SMART START guide
canonical-web-and-design/ubuntu.com pull request #8303
Opened 2020-09-16 09:05 UTC by carkod

## Done

- Add discourse module

## QA

- Open the demo and navigate to `/docs`

## Issue / Card

Fixes #

2020-09-16 09:05 UTC, webteam-app commented
Demo starting at https://ubuntu-com-8303.demos.haus

2020-09-16 16:21 UTC, pmahnke commented
I am getting a 

```
requests.exceptions.HTTPError
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://discourse.ubuntu.com/t/15433.json```

error

2020-09-17 11:48 UTC, carkod commented
> I am getting a
> 
> ```
> requests.exceptions.HTTPError
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://discourse.ubuntu.com/t/15433.json```
> 
> error
> ```

Fixed. Can you take a look now?

2020-09-17 14:02 UTC, anthonydillon requested changes
Please update the content to have h1 followed by h2 for SEO. Comment in the code.

2020-09-17 15:08 UTC, carkod commented
> Please update the content to have h1 followed by h2 for SEO. Comment in the code.

Done

2020-09-17 16:14 UTC, anthonydillon approved these changes
LGTM with one small change suggested.

2020-09-17 16:14 UTC, anthonydillon commented on templates/smart-start/document.html
> +{% block title %} {{ document.title }} | Server documentation{% endblock %}
```suggestion
{% block title %} {{ document.title }} | Smart start{% endblock %}
```

2020-09-18 08:42 UTC, merged