Security series webinar
canonical-web-and-design/ubuntu.com pull request #8365
Opened 2020-09-25 14:39 UTC by bethcollins92

## Done

- Build takeover
- Build even page at `/security-series`
- Add takeover to `takeovers/index.html`
- Add takeover to `index.html`
- Build [social banner](https://tools.demos.haus/?title=Ubuntu+Security%3A+Security+and+compliance&subtitle=The+full+Ubuntu+security+story.+Learn+how+our+teams+are+securing+all+your+open+source%2C+from+cloud+to+edge.&illustration_url=https%3A%2F%2Fassets.ubuntu.com%2Fv1%2F1899df43-ubuntu-advantage-circular_white.svg&background=grad#banner-form-modal)

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/security-series
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check the site matches the [design](https://user-images.githubusercontent.com/65166314/93861516-ed194c80-fcc0-11ea-933e-a87dca1a7375.png) and the [brief](https://docs.google.com/document/d/1A7JDBRZ_tuEvteE1pVA9_rV-oJUq1_DuT7GmO6zVCXM/edit#)
- Check takeover matches [design](https://github.com/canonical-web-and-design/web-squad/issues/3114) and [brief](https://docs.google.com/document/d/1duufuOPuy6asv-i9qtGNs3y1VLRO67GYaOfwE9OGQmw/edit)

## Issue / Card

Fixes #8184 

## Screenshots

![image](https://user-images.githubusercontent.com/58959073/94280215-0fbb9780-ff45-11ea-9f9c-f32accde0249.png)

2020-09-25 14:39 UTC, webteam-app commented
Demo starting at https://ubuntu-com-8365.demos.haus

2020-09-28 12:49 UTC, pmahnke commented
@Khutch25 why not 'Register for the webinar' ?  I know you know they are all webinars, but will someone landing on the page from an ad?

2020-09-28 13:05 UTC, pmahnke requested changes
A few comments inline.

2020-09-28 13:05 UTC, pmahnke commented on templates/security-series/index.html
> +      <p>
some of the space around the illustrations is off

![image](https://user-images.githubusercontent.com/441217/94435740-7209d780-0193-11eb-89d5-73fdb67b9bd1.png)


some are in `p` tags and some have `u-sv1` can you check them?

2020-09-28 13:58 UTC, Khutch25 commented
> @Khutch25 why not 'Register for the webinar' ? I know you know they are all webinars, but will someone landing on the page from an ad?

Yes, you are right. Is it too late to align them all to 'Register for webinar' with the offsite/new tab link icon? 

I've made updates to the copy doc to reflect this - https://docs.google.com/document/d/1A7JDBRZ_tuEvteE1pVA9_rV-oJUq1_DuT7GmO6zVCXM/edit

2020-09-28 14:10 UTC, bethcollins92 commented on templates/security-series/index.html
> +         attrs={"class": ""},
Spoken to @meralonso and she said these illustrations are going to be videos in the future so they can't be hidden on small screens

2020-09-28 14:19 UTC, bethcollins92 commented
Ready for another review

2020-09-28 14:45 UTC, pmahnke approved these changes
one last comment then good to go

2020-09-28 14:45 UTC, pmahnke commented on templates/security-series/index.html
> +    <div class="col-6">
you need a bit of space between this and the next row
```suggestion
    <div class="col-6 u-sv3">
```

2020-09-28 16:32 UTC, pmahnke commented
@bethcollins92 can you also take down the telco virtual event takeover with this? cc @SirSamTumless

2020-09-29 14:20 UTC, meralonso commented
Hey @bethcollins92 I'm happy with the layout but all illustrations are pixelated for some reason - could you please have a look into that? 

![Screenshot 2020-09-29 at 15 16 11](https://user-images.githubusercontent.com/65166314/94570953-b10d5b00-026f-11eb-835f-693d5ff6a52a.png)

![Screenshot 2020-09-29 at 15 20 11](https://user-images.githubusercontent.com/65166314/94570957-b1a5f180-026f-11eb-9c48-598773996c9d.png)

2020-09-29 15:20 UTC, meralonso commented
> Hey @bethcollins92 I'm happy with the layout but all illustrations are pixelated for some reason - could you please have a look into that?
> 
> ![Screenshot 2020-09-29 at 15 16 11](https://user-images.githubusercontent.com/65166314/94570953-b10d5b00-026f-11eb-835f-693d5ff6a52a.png)
> 
> ![Screenshot 2020-09-29 at 15 20 11](https://user-images.githubusercontent.com/65166314/94570957-b1a5f180-026f-11eb-9c48-598773996c9d.png)

@bethcollins92 according to @sowasred2012 the pixelated images seems to be a different issue and he's going to flag that up

2020-09-29 15:43 UTC, merged

2020-09-29 17:17 UTC, anthonydillon commented
@bethcollins92 Can you reset the commits in this PR and ask Steve for help force pushing to master to fix the history and propose a new PR with cherry picked commits please.