Add Snap Store terms of service
canonical-web-and-design/ubuntu.com pull request #8459
Opened 2020-10-13 14:20 UTC by bethcollins92

## Done

- Add Snap Store terms of service to `legal/terms-and-policies/snap-store-terms`
- Add blurb box on `/legal/terms-and-policies` 

**Known difference**:
- Privacy notice link in _13. Personal data_ links to privacy page which has not yet been updated.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/terms-and-policies/snap-store-terms and check against [copy doc](https://docs.google.com/document/d/1liRDdiO4JIIV43hqNckIk0ONGYW5MeaLuW-4U2HZky4/edit#)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check new Snap Store blurb box on http://0.0.0.0:8001/legal/terms-and-policies 

## Issue / Card

Fixes [#8443](https://github.com/canonical-web-and-design/ubuntu.com/issues/8443)

2020-10-13 14:25 UTC, webteam-app commented
Demo starting at https://ubuntu-com-8459.demos.haus

2020-10-14 12:51 UTC, pmahnke commented
do you want to update this now the other one is approved?

2020-10-14 13:35 UTC, bethcollins92 commented
@pmahnke I did link to the right privacy notice page, but just that it wasn't yet updated. So once that one is deployed it will be correct

2020-10-14 14:06 UTC, pmahnke requested changes
A few links to update.

2020-10-14 14:06 UTC, pmahnke commented on templates/legal/terms-and-policies/index.html
> +      <p>The terms for use of our Snap Store and services delivered via Snapcraft.io.</p>
```suggestion
      <p>The terms for use of our Snap Store and services delivered via snapcraft.io.</p>
```

2020-10-14 14:06 UTC, pmahnke commented on templates/legal/terms-and-policies/snap-store-terms.html
> +     You must be at least 13 years old to use the Snap Store. If you are aged between 13 and 18, we require your parent's or legal guardian's consent to create a Snap Store account or use the Snap St
```suggestion
     You must be at least 13 years old to use the Snap Store. If you are aged between 13 and 18, we require your parent's or legal guardian's consent to create a Snap Store account or use the Snap Store. Please contact us at <a href="mailto:legal@canonical.com">legal@canonical.com</a>. 
```

2020-10-14 14:06 UTC, pmahnke commented on templates/legal/terms-and-policies/snap-store-terms.html
> +       <li class="p-list__item">15.4 Any notices should be sent by email to legal@canonical.com or by registered post to Canonical Group Limited, 5th Floor, Blue Fin Building, 110 Southwark Street, L
```suggestion
       <li class="p-list__item">15.4 Any notices should be sent by email to <a href="mailto:legal@canonical.com">legal@canonical.com</a> or by registered post to Canonical Group Limited, 5th Floor, Blue Fin Building, 110 Southwark Street, London, England, SE1 0SU.</li>
```

2020-10-14 14:45 UTC, pmahnke approved these changes
+1

2020-10-14 14:48 UTC, merged