Validate VAT number on input change for logged in users
canonical-web-and-design/ubuntu.com pull request #8601
Opened 2020-10-26 16:19 UTC by sowasred2012

## Done

For logged in users, we can validate any VAT number they input at the same time we make the call to get their VAT total (for guest users, this validation can only occur when they've clicked "Continue" and their account has been created).

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/advantage/subscribe
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Make sure you're logged in
- Select a product, add it to your cart, and click "Buy" to launch the payment modal
- Fill out the card and address details, and select United Kingdom as your country
- Type some nonsense into the VAT number field
- See that, after a short delay, the field displays an error

2020-10-26 16:19 UTC, webteam-app commented
Demo starting at https://ubuntu-com-8601.demos.haus

2020-10-26 16:21 UTC, frankban approved these changes
Looks good!

2020-10-26 16:27 UTC, frankban commented
QA ok.

2020-10-26 19:55 UTC, anthonydillon commented
Works well, although a few issues:
- If you blur the input before the error returns the user doesn't get any error and can submit
- the example VAT codes both error. A good example is "GB 123 1234 12 123 or GB 123 4567 89 1234"

2020-10-26 19:56 UTC, anthonydillon requested changes
Few questions in the comment above.

2020-10-27 09:49 UTC, sowasred2012 commented
@anthonydillon good points - updated

2020-10-27 12:42 UTC, anthonydillon approved these changes
LGTM :+1:

2020-10-27 13:33 UTC, merged