Copy update on /support
canonical-web-and-design/ubuntu.com pull request #8625
Opened 2020-10-28 16:35 UTC by bethcollins92

## Done

- Rebuild `/support` page

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/support
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check page against [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit#)

## Issue / Card

Fixes [#3365](https://github.com/canonical-web-and-design/web-squad/issues/3365)

2020-10-28 16:35 UTC, webteam-app commented
Demo starting at https://ubuntu-com-8625.demos.haus

2020-10-29 08:49 UTC, pmahnke commented
@lechsandecki @bethcollins92 I have asked a number of questions in the copy doc that need to be reviewed before we qa this.  Sorry

2020-10-29 09:37 UTC, lechsandecki commented
Thank you, Peter. I just replied to your comments.

On Thu, Oct 29, 2020 at 8:50 AM Peter Mahnke <notifications@github.com>
wrote:

> @lechsandecki <https://github.com/lechsandecki> @bethcollins92
> <https://github.com/bethcollins92> I have asked a number of questions in
> the copy doc that need to be reviewed before we qa this. Sorry
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/canonical-web-and-design/ubuntu.com/pull/8625#issuecomment-718489641>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANICHVVTPRSIIVEKTSGOKKTSNEUDZANCNFSM4TCSHYDA>
> .
>

2020-10-30 10:00 UTC, bethcollins92 commented
@pmahnke Ready for review

2020-10-30 10:44 UTC, pmahnke requested changes
suggestions in line also, I think we need to redo the apps section... I will make a comment in a second

2020-10-30 10:44 UTC, pmahnke commented on templates/support/index.html
> +        <a href="/support/contact-us?product=support-overview" class="p-button--positive">Contact us</a>
this should have a class to open the modal

2020-10-30 10:44 UTC, pmahnke commented on templates/support/index.html
> +        <a href="https://buy.ubuntu.com/">Supported applications&nbsp;&rsaquo;</a>
this should just be an anchor link to the apps support section, no?

2020-10-30 10:44 UTC, pmahnke commented on templates/support/index.html
> +<section class="p-strip">
needs an id for the anchor

2020-10-30 10:44 UTC, pmahnke commented on templates/support/index.html
> +          <td class="u-align--center">X</td>
these X's should be `&ndash;`s

2020-10-30 13:05 UTC, bethcollins92 commented
Ready for re-review

2020-10-30 13:28 UTC, spencerbygraves commented
@bethcollins92 I think you're missing the mongodb logo:

![image](https://user-images.githubusercontent.com/9105999/97710508-bd294a00-1ab3-11eb-8f88-0cbdfc9a0611.png)

2020-10-30 14:25 UTC, pmahnke commented
@spencerbygraves it isn't missing, look at /managed... we were told not to use it.

2020-10-30 14:27 UTC, pmahnke approved these changes
+1

2020-10-30 14:33 UTC, spencerbygraves commented
>we were told not to use it.

Ok, fair enough.

2020-10-30 14:36 UTC, merged