Update product-cards.html
canonical-web-and-design/ubuntu.com pull request #8731
Opened 2020-11-12 12:32 UTC by andreeamun

## Done

Add dynamic blog product cards in place of Marketo RTPs.
Eg. on blog post tagged kubeflow, a list of relevant cards is added to the blog post right column and one is made visible at random. This PR comes with instrumentation to assess CTR on cards.

This PR comes with cards for the following blog posts:
  - [IoT](https://ubuntu.com/blog/tag/IoT)
  - [Event](https://ubuntu.com/blog/tag/Event)
  - [telco](https://ubuntu.com/blog/tag/telco)

- The list of cards is maintained by PMs and Mktg and ongoing card code maintenance will be on Mktg.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Ensure blog posts listed under:
  - [IoT](https://ubuntu-com-8249.demos.haus/blog/tag/IoT)
  - [Event](https://ubuntu-com-8249.demos.haus/blog/tag/Event)
  - [telco](https://ubuntu-com-8249.demos.haus/blog/tag/telco)

  ...have related product cards displayed right of the article (bottom on mobile), that their display is randomized (eg. for Kubeflow) and that links are working.

2020-11-12 12:32 UTC, webteam-app commented
Demo starting at https://ubuntu-com-8731.demos.haus

2020-11-12 15:52 UTC, pmahnke requested changes
This won't work this way.  the logic has to be all in one block like:

```
{% if article.tags and XXXX in article.tags %}
   {% inlcude "file" %}
{% elif article.tags and XXXX in article.tags %}
   {% inlcude "file" %}
{% if article.tags and XXXX in article.tags %}
   {% inlcude "file" %}
{% endif %}
```

Yours are not in that flow.  Also your includes have an extra `}` which isn't right.

And finally, there is no way to test this without your other PRs being merged.  And the CI that tests the site shouldn't work either with out them.  The better way would be to add the card and the logic in a single PR, perhas one for each card tag?

Does that make sense?

Are you running this locally?  That would help you do this.  I will ask Robin to contact you tomorrow to learn how.

2020-11-12 17:23 UTC, andreeamun commented
Thank you for the explanations.

Some of the things make sense, some other are very blurry. I will ask Robin tomorrow to make sure I understand correctly.

Usually, I run them locally.

2020-11-16 11:45 UTC, nottrobin commented
I've merged all the templates into this PR, so that the demo will display the new cards.

E.g. look at https://ubuntu-com-8731.demos.haus/blog/edge-native-linux - you can see the new smart start card on the right hand side.

2020-11-16 16:51 UTC, pmahnke requested changes
A few inline comments

2020-11-16 16:51 UTC, pmahnke commented on templates/blog/product-cards/_financialservices-awerness.html
> +  <img class="p-card__thumbnail" src="https://assets.ubuntu.com/v1/dcbd63b9-9outof10.JPG" alt="9outof10financialinstitutions">
```suggestion
  <img src="https://assets.ubuntu.com/v1/dcbd63b9-9outof10.JPG" alt="9outof10financialinstitutions">
```
remove this class to make the image full sidebar width

2020-11-16 16:51 UTC, pmahnke commented on templates/blog/product-cards/_telco.html
> +  <p><a href="/telco">Learn more about Ubuntu for telco</a></p>
```suggestion
  <p><a href="/telco">Learn more about Ubuntu for telco&nbsp;&rsaquo;</a></p>
```
right arror

2020-11-16 16:51 UTC, pmahnke commented on templates/blog/product-cards/_smartstart.html
> +  <p><a href="/smartstart">Get your IoT device to market fast</a></p>
```suggestion
  <p><a href="/smartstart">Get your IoT device to market fast&nbsp;&rsaquo;</a></p>
```
right arrow

2020-11-16 16:51 UTC, pmahnke commented on templates/blog/product-cards/_financialservices-awerness.html
> +  <p><a href="/engage/finance">Learn more about Ubuntu</a></p>
```suggestion
  <p><a href="/engage/finance">Learn more about Ubuntu&nbsp;&rsaquo;</a></p>
```
right arrow

2020-11-16 16:51 UTC, pmahnke commented on templates/blog/product-cards/_IoT_appstore.html
> +  <p><a href="/internet-of-things/appstore">Build your IoT app ecosystem</a></p>
```suggestion
  <p><a href="/internet-of-things/appstore">Build your IoT app ecosystem&nbsp;&rsaquo;</a></p>
```
right arrow

2020-11-16 17:38 UTC, pmahnke approved these changes

2020-11-16 17:38 UTC, merged