WIP Core docs
canonical-web-and-design/ubuntu.com pull request #8934
Opened 2020-12-15 17:02 UTC by carkod

## Done

- [List of work items including drive-bys.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

2020-12-15 17:02 UTC, webteam-app commented
Demo starting at https://ubuntu-com-8934.demos.haus

2021-01-06 11:37 UTC, nottrobin commented on webapp/app.py
> +core_modemmanager_docs = Docs(
I think `modemmanager` should be 2 words:

```suggestion
core_modem_manager_docs = Docs(
```

2021-01-06 11:38 UTC, nottrobin commented on webapp/app.py
> +core_networkmanager_docs = Docs(
Same here, and the others going down

2021-01-06 12:10 UTC, nottrobin requested changes
## Breadcrumbs

These pages should have breadcrumbs that place them in the core section:

![image](https://user-images.githubusercontent.com/519935/103766721-3777cc80-5017-11eb-92c6-739f41436307.png)

(For an example, see the server docs section)

I guess you should probably place each set of documentation in this list.

> Core | Overview | Docs

And then for the other documentation sections, you probably want their breadcrumb to appear on the end of that list, but only when you're in that section:

> Core | Overview | Docs | Network manager docs

Or something.

## Other issues:

- https://ubuntu-com-8934.demos.haus/core/docs/audio-management -> pulseaudio link doesn't work
- https://ubuntu-com-8934.demos.haus/core/docs/bluetooth-management -> Bluez link 404s
- https://ubuntu-com-8934.demos.haus/core/docs/networkmanager -> "Release notes" and "Report a bug" don't work

2021-01-06 17:48 UTC, carkod commented
> ## Breadcrumbs
> These pages should have breadcrumbs that place them in the core section:
> 
> ![image](https://user-images.githubusercontent.com/519935/103766721-3777cc80-5017-11eb-92c6-739f41436307.png)
> 
> (For an example, see the server docs section)
> 
> I guess you should probably place each set of documentation in this list.
> 
> > Core | Overview | Docs
> 
> And then for the other documentation sections, you probably want their breadcrumb to appear on the end of that list, but only when you're in that section:
> 
> > Core | Overview | Docs | Network manager docs
> 
> Or something.
> 
> ## Other issues:
> * https://ubuntu-com-8934.demos.haus/core/docs/audio-management -> pulseaudio link doesn't work
> * https://ubuntu-com-8934.demos.haus/core/docs/bluetooth-management -> Bluez link 404s
> * https://ubuntu-com-8934.demos.haus/core/docs/networkmanager -> "Release notes" and "Report a bug" don't work

- Pulseaudio is deprecated https://discourse.ubuntu.com/t/access-from-other-snaps/19900 I don't know what's their plan next
- About breadcrumb links, I don't think this is ready to be "published"? Like mentioned, there are links broken and documentation that needs to be removed or replaced, so if we enable those links, people will start reporting bugs when they access them
Everything else mentioned is fixed

2021-01-06 17:48 UTC, carkod commented on static/js/src/chart-data.js
> +    status: "MATCHING_OPENSTACK_RELEASE_SUPPORT",
prettier was failing if I didn't do this...

2021-01-08 00:17 UTC, nottrobin commented
> Pulseaudio is deprecated https://discourse.ubuntu.com/t/access-from-other-snaps/19900 I don't know what's their plan next

I see. We need to work out whether to remove the link or add the documentation. Who do we ask?

> About breadcrumb links, I don't think this is ready to be "published"? Like mentioned, there are links broken and documentation that needs to be removed or replaced, so if we enable those links, people will start reporting bugs when they access them

Can you please add the bookmarks bar anyway? That's an important component of the page. If it's not for hard launch yet, then don't include the `Docs` link in the breadcrumb for the core overview page, but you can still make it show up on the docs page itself.

Basically, I think you want to add "Docs" to [the Core navigation](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/navigation.yaml#L987) with `hidden: True`.

2021-01-11 12:37 UTC, carkod commented
> > Pulseaudio is deprecated https://discourse.ubuntu.com/t/access-from-other-snaps/19900 I don't know what's their plan next
> 
> I see. We need to work out whether to remove the link or add the documentation. Who do we ask?
> 
> > About breadcrumb links, I don't think this is ready to be "published"? Like mentioned, there are links broken and documentation that needs to be removed or replaced, so if we enable those links, people will start reporting bugs when they access them
> 
> Can you please add the bookmarks bar anyway? That's an important component of the page. If it's not for hard launch yet, then don't include the `Docs` link in the breadcrumb for the core overview page, but you can still make it show up on the docs page itself.
> 
> Basically, I think you want to add "Docs" to [the Core navigation](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/navigation.yaml#L987) with `hidden: True`.

Done

2021-01-12 09:41 UTC, nottrobin commented
I don't see it:

![image](https://user-images.githubusercontent.com/519935/104297087-57493d80-54ba-11eb-850c-46c961fbfb5a.png)

2021-01-12 19:08 UTC, carkod commented
> I don't see it:
> 
> ![image](https://user-images.githubusercontent.com/519935/104297087-57493d80-54ba-11eb-850c-46c961fbfb5a.png)

Fixed. `Persistent: True` was missing

2021-01-12 23:24 UTC, nottrobin approved these changes
Nice work. I like how you've done the secondary nav for "network management" etc. Very neat.

:+1:

2021-01-13 09:52 UTC, merged