WIP: Update /core page
canonical-web-and-design/ubuntu.com pull request #9142
Opened 2021-02-01 15:05 UTC by bethcollins92

## Done

- Update /core page
- Add `/smartstart` and `tutorials` to the nav 
- **NOTE**: Waiting on video for hero, and answer from Amber about moving `/smartstart` bubble

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/core
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check page against [copydoc](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#heading=h.cc4g322ve6sn) 

## Issue / Card

Fixes [#3643](https://github.com/canonical-web-and-design/web-squad/issues/3643) and [#3668](https://github.com/canonical-web-and-design/web-squad/issues/3668)

2021-02-01 15:05 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9142.demos.haus

2021-02-01 17:46 UTC, anasereijo commented
🥇 LGTM

2021-02-02 09:06 UTC, pmahnke requested changes
a few comments inline, very close

2021-02-02 09:06 UTC, pmahnke commented on static/sass/_pattern_strip.scss
> +    background-position: top left, top right, center 66.4%, left top;
I am seeing the black line now. 66.5 works better for me... test before you accept this.
```suggestion
    background-position: top left, top right, center 66.5%, left top;
```

2021-02-02 09:06 UTC, pmahnke commented on templates/core/index.html
> +      <p>
```suggestion
      <p class="u-sv3">
```

I think there needs to be a bit more space,

2021-02-02 09:35 UTC, SirSamTumless commented
https://www.youtube.com/watch?v=qjmj2cy4LLA&feature=youtu.be Video here @bethcollins92

2021-02-02 10:13 UTC, pmahnke approved these changes
+1

2021-02-02 10:51 UTC, merged