Rebuild /ai/services page
canonical-web-and-design/ubuntu.com pull request #9219
Opened 2021-02-09 14:54 UTC by bethcollins92

## Done

- Rebuild `/ai/services` page
- Update learn more section to include dynamic AI blog post list

## QA

- View page at: 
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check page against [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit#)

## Issue / Card

Fixes [#3767](https://github.com/canonical-web-and-design/web-squad/issues/3767)

2021-02-09 14:54 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9219.demos.haus

2021-02-10 09:50 UTC, spencerbygraves commented
Thanks @bethcollins92, a couple of changes from me please.

Can the "Learn more..." title in the last section be h2 please. Can we also update the partners section, I've moved the logos and balanced out the sizes a bit.

Thanks.

![image](https://user-images.githubusercontent.com/9105999/107493366-6c7ebe00-6b85-11eb-8207-ee4616ab9890.png)

2021-02-10 09:51 UTC, spencerbygraves commented
@bethcollins92 I didn't mean to remove the button! Thanks.

2021-02-10 10:59 UTC, bethcollins92 commented
Thanks @spencerbygraves 👍🏼  ready for a re-review please

2021-02-10 12:23 UTC, spencerbygraves commented
Thanks @bethcollins92 👍

2021-02-11 09:17 UTC, pmahnke requested changes
Some changes inline.  I also asked about the double list of blog posts @RFMVasconcelos and @bethcollins92

2021-02-11 09:17 UTC, pmahnke commented on templates/ai/services.html
> +        <a class="p-link--external p-button--neutral" href="https://assets.ubuntu.com/v1/ee5a96f3-Kubeflow+Training+Curriculum.pdf?_ga=2.202291033.951646160.1607941648-154096706.1586788067">See Curri
```suggestion
        <a class="p-button--neutral" href="https://assets.ubuntu.com/v1/ee5a96f3-Kubeflow+Training+Curriculum.pdf?_ga=2.202291033.951646160.1607941648-154096706.1586788067">See the curriculum</a>
```

We don't do external links for assets.u.c

2021-02-11 09:17 UTC, pmahnke commented on templates/ai/services.html
> +          <a class="p-link--external p-link--inverted" href="https://assets.ubuntu.com/v1/197d9867-Charmed_Kubeflow_Kubernetes_10.11.20+%282%29.pdf">Download datasheet</a>
```suggestion
          <a class="p-link--inverted" href="https://assets.ubuntu.com/v1/197d9867-Charmed_Kubeflow_Kubernetes_10.11.20+%282%29.pdf">Download the datasheet</a>
```

again, not external, and we need definate articles

2021-02-11 09:17 UTC, pmahnke commented on templates/ai/services.html
> +        <a class="p-button--positive js-invoke-modal" href="/ai/contact-us?product=ai-index">Talk to experts</a>
```suggestion
        <a class="p-button--positive js-invoke-modal" href="/ai/contact-us?product=ai-index">Talk to the experts</a>
```

add 'the'

2021-02-12 14:13 UTC, bethcollins92 commented
@pmahnke Added the Kubeflow news section, if you would mind taking a look and QA-ing? The thank you message appears now, but I'm not too sure if/how to check the form is submitting correctly. I copied the marketo form ID from the kubeflow-news.com page

2021-02-12 14:41 UTC, pmahnke commented
@bethcollins92 the form doesn't work, you are missing a lot of hidden fields

```
      <input type="hidden" name="Consent_to_Processing__c" value="Yes">
      <input type="hidden" name="formid" value="3415">
      <input type="hidden" name="formVid" value="3415">
      <input type="hidden" name="lpId" value="">
      <input type="hidden" name="munchkinId" value="066-EOV-335">
      <input type="hidden" name="lpurl" value="">
 ```

2021-02-12 14:50 UTC, bethcollins92 commented
@pmahnke thanks, added those in now

2021-02-12 14:56 UTC, pmahnke approved these changes
works! thanks

2021-02-12 15:04 UTC, merged