Update ROS contact-us modal
canonical-web-and-design/ubuntu.com pull request #9334
Opened 2021-03-02 15:41 UTC by pmahnke

## Done

- Update ROS contact-us modal

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics#get-in-touch
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to the [copy doc](https://docs.google.com/document/d/1vDbdFBrG6tWDUb5z5ltny_7d-GZU78wS8K7Nru2BSj8/edit#)

2021-03-02 15:41 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9334.demos.haus

2021-03-02 15:51 UTC, GAN-Canonical commented on templates/shared/forms/interactive/robotics_ros.html
> +      <p id="modal-description" class="u-no-max-width u-no-margin--bottom">Tell us about your project so we can bring the right team to the conversation. If the form doesn't address your questions, p
Please add " please press next and submit your inquiry in the text block below.

2021-03-02 15:54 UTC, GAN-Canonical requested changes

2021-03-02 15:54 UTC, GAN-Canonical commented on templates/shared/forms/interactive/robotics_ros.html
>            </div>
We have a blank option

2021-03-02 15:54 UTC, GAN-Canonical commented on templates/shared/forms/interactive/robotics_ros.html
> +      <p id="modal-description" class="u-no-max-width u-no-margin--bottom">Tell us about your project so we can bring the right team to the conversation. If the form doesn't address your questions, p
Please add " please press next and submit your inquiry in the text block below.

2021-03-02 15:55 UTC, GAN-Canonical commented on templates/shared/forms/interactive/robotics_ros.html
>            </div>
![form](https://user-images.githubusercontent.com/78618068/109675481-c0bb0380-7b6f-11eb-9694-1a1fc18936ac.png)

2021-03-03 10:08 UTC, GAN-Canonical approved these changes

2021-03-03 10:09 UTC, GAN-Canonical approved these changes

2021-03-03 10:11 UTC, GAN-Canonical approved these changes

2021-03-03 16:41 UTC, SirSamTumless approved these changes

2021-03-04 08:39 UTC, merged