WIP: Openstack compare copy update
canonical-web-and-design/ubuntu.com pull request #9461
Opened 2021-03-25 15:36 UTC by jpmartinspt

## Done

Rebuild the page as specified in https://github.com/canonical-web-and-design/web-squad/issues/3939

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

Fixes https://github.com/canonical-web-and-design/web-squad/issues/3939

2021-03-25 15:36 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9461.demos.haus

2021-03-26 09:39 UTC, anasereijo commented
@jpmartinspt thanks for doing this. 
In my opinion, this needs design time (and UX too probably). @SirSamTumless could you allocate some time for the next iteration?

2021-03-26 09:40 UTC, cristinadresch commented
@jpmartinspt is this ready for code review?

2021-03-29 08:39 UTC, SirSamTumless commented
@carkod Why's this blocked?

2021-03-29 09:02 UTC, anasereijo commented
@SirSamTumless as discussed, here are my thoughts:

If we keep adding stuff to this table we need to rethink the whole thing as it is very confusing now and hard to go through the info.  We are now showing a mix of things such as expanding text, icons, $$ and ratings.

The purpose of using an expanding table was so the user could compare easily and quickly compare the 3 companies and then read a bit more about Canonical (by expanding the rows). I don't think we are serving that purpose anymore. 

If we really need to keep all these things I think we will need UX help.

2021-03-29 10:09 UTC, clagom commented
I agree with @anasereijo, this needs UX too: with the new elements in there I don't think the accordion pattern works as well. Thanks for flagging this Ana.
@SirSamTumless Do we still need the comparison at all? Do we have a brief for the changes? We need more context.

2021-03-30 10:36 UTC, SirSamTumless commented
@tytus-kurek The team have looked at this (see the demo link) and with the rating, it really doesn't work. I think this needs a rethink. Also, I personally don't think the ratings are great - we've given ourselves full ratings for everything which screams inauthenticity to me.

2021-03-30 11:27 UTC, tytus-kurek commented
@SirSamTumless what is the exact problem with the new layout?

Is it that we use ratings? I discussed that with Alex some time ago and we are already using ratings at ubuntu.com/kubernetes/compare which was another iteration of the "compare" pages, so the goal was to standardise on a common framework.

Is it that we gave ourselves 5/5 everywhere? Again, we've done the same at ubuntu.com/kubernetes/compare and it passed the UX review. Also, this is not much different from what everyone is doing. Have a look at https://platform9.com/openstack-distributions-comparison/ , for example. They undermine any other OpenStack distributions while highlighting the benefits of Platform9 Managed OpenStack.

Is it that we use "+" next to the ratings? We can get rid of it if needed.

To sum up, I'm happy to adjust to a company-wide standard for the "compare" pages creation, but I'd like to make sure I'm not the only one who's tasked to do that.

2021-03-30 12:08 UTC, clagom commented
@tytus-kurek I think the main point is the readability of the table. If you put side by side our table with the link you shared I think the difference is very prominent. Our table has price ($$$), check icons, rating (of what exactly?) and + to open up more information. The link you shared compares just a X or a icon/logo of the product. I think we just need to work on the interaction (do we need "+" at all? more info at all?) and to simplify the content if we can? As it is, makes users wonder what is going on and takes time to engage and interpret what we want to say.
In short, I think we would like to improve it.
CC @SirSamTumless @anasereijo

2021-04-06 08:44 UTC, tytus-kurek commented
@SirSamTumless Let me suggest something. Since you already have a demo of the page with all the recent changes, why don't we update the parts of the page you're happy with (the title, the top paragraph, other paragraphs, table structure, etc.) and continue working on the exact layout of the comparison table in parallel. I'd be happy to adjust to whatever you come up with when updating K8s pages. Would that work for you?

2021-04-06 09:22 UTC, tytus-kurek commented
@clagom ^^ sorry, I didn't realize the latest comment came from you.

2021-04-07 14:32 UTC, jpmartinspt commented
@clagom @anasereijo @SirSamTumless  @tytus-kurek I have removed most of the things we don't like about that table. are we good to merge it as it stands now and think about a better layout on a follow-up PR?

2021-04-07 15:58 UTC, tytus-kurek commented
@jpmartinspt LGTM and I'm happy to continue working on a better layout in the future.

2021-04-07 16:13 UTC, anasereijo commented
@jpmartinspt LGTM and yes, we should look into this in the near future.

I have some suggestions:

- [ ] row elements are not vertically aligned.
<img width="1285" alt="Screenshot 2021-04-07 at 17 06 18" src="https://user-images.githubusercontent.com/36884067/113898311-a8b84e80-97c3-11eb-8616-294f9ba22219.png">

- [ ] Quote: can you make it look like this example? You can check the code [here](https://ubuntu.com/0_docs/content_strips) (scroll down)

<img width="2556" alt="Screenshot 2021-04-07 at 17 10 25" src="https://user-images.githubusercontent.com/36884067/113898872-29774a80-97c4-11eb-9b53-16e658d7839d.png">

- [ ] after changing the quote styling make the following section (More economical than Red Hat...) white background and the next one light-grey and so on.

2021-04-07 16:15 UTC, clagom commented
Thanks @jpmartinspt ;)

2021-04-07 16:36 UTC, jpmartinspt commented
@anasereijo updated!

2021-04-07 16:42 UTC, anasereijo commented
lgtm 👍 thanks`!

2021-04-07 17:11 UTC, anthonydillon requested changes
Some comments in the code and its missing the last section "More cost-efficient than public clouds" from the copy doc.

2021-04-07 17:11 UTC, anthonydillon commented on templates/openstack/compare.html
>                <p>Charmed OpenStack provides support for KVM hypervisors. Other hypervisor out of the box are available through the consulting services.</p>
This content is different in the copy doc

2021-04-07 17:11 UTC, anthonydillon commented on templates/openstack/compare.html
> +      <p>Instead of relying on random interconnected tools, Canonical leverages the concept of operators for OpenStack deployments, operations and upgrades. The OpenStack Charmed Operators (OpenStack
OpenStack Charms should be a link

2021-04-07 17:11 UTC, anthonydillon commented on templates/openstack/compare.html
>        <h2>Open source, unlike VMware</h2>
This one doesn't have a comma in the copy doc

2021-04-07 17:11 UTC, anthonydillon commented on templates/openstack/compare.html
> +      <p>Canonical's Charmed OpenStack is fully open source which allows it to benefit from a broader community, faster development process and wider selection of technology choices than those availa
This one has different content in the copy doc

2021-04-07 17:12 UTC, anthonydillon commented on templates/openstack/compare.html
> +      <p>Let our private cloud team help with:</p>
This section has suggestions in the copy doc

2021-04-07 17:36 UTC, jpmartinspt commented
@anthonydillon everything should be fixed now.

2021-04-07 18:17 UTC, anthonydillon approved these changes
LGTM with a small request

2021-04-07 18:17 UTC, anthonydillon commented on templates/openstack/compare.html
> +              <p><a href="https://maas.io">MAAS</a> is a bare-metal provisioning tool that turns a data centre into a true bare metal cloud.</p>
All the external links should have a `p-link--external` class on them.

2021-04-07 18:32 UTC, merged

2021-04-08 02:53 UTC, jpmartinspt commented
@anthonydillon sorry I missed the requests, I'll open another PR tomorrow.