Update instruction copy
canonical-web-and-design/ubuntu.com pull request #9669
Opened 2021-04-30 10:40 UTC by ClementChaumel

## Done

- Update instruction copy for 16.04 and 18.04 according to https://github.com/canonical-web-and-design/ubuntu.com/issues/9517#issuecomment-820183733

## QA

-  https://ubuntu-com-9547.demos.haus/advantage?test_backend=true

## Issue / Card

Fixes #9517

## Screenshots

![image](https://user-images.githubusercontent.com/11927929/114892893-7505a600-9e0d-11eb-858d-91e61a413ca5.png)

2021-04-30 10:40 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9669.demos.haus

2021-04-30 10:44 UTC, ClementChaumel commented
@lechsandecki here are the changes to the instructions. Please review it and provide instruction for the 16.04 and 18.04 changes thanks!

2021-05-02 18:03 UTC, lechsandecki requested changes

2021-05-02 18:03 UTC, lechsandecki commented on templates/advantage/table/_attached-machines.html
> +          <p class="u-no-margin--bottom">Once installed or if you’re using Ubuntu 14.04 ESM or 20.04 LTS, first attach each machine.</p>
I'd drop that. I suggest that, on this page, we keep the following:

to attach a machine: sudo ua abc
to detach a machine: sudo ua def

Please ensure that you have the latest version of the ua client installed: apt-get upgrade

2021-05-02 18:03 UTC, lechsandecki commented on templates/advantage/table/_attached-machines.html
> +          <p class="u-no-margin--bottom">Once installed or if you’re using Ubuntu 14.04 ESM or 20.04 LTS, first attach each machine.</p>
we also need to update the ESM screen (it's now 14.04 or 16.04, not just 14.04)
Similarly, Livepach can get activated via the ua client for each Ubuntu LTS now. We don't need separate "Ubuntu 16.04 LTS and 18.04 LTS" instructions anymore

2021-05-04 10:14 UTC, albertkol commented
@ClementChaumel you broke the table

![image](https://user-images.githubusercontent.com/6387619/116989651-ec6e7d00-acc9-11eb-8bcb-f8cfdddc0333.png)

2021-05-05 08:03 UTC, ClementChaumel commented
I've updated the copy according to your review @lechsandecki, please take another look:
![image](https://user-images.githubusercontent.com/11927929/117112198-002ce880-ad89-11eb-953f-7909b47e2326.png)
![image](https://user-images.githubusercontent.com/11927929/117112241-0de26e00-ad89-11eb-90b9-bed2e5be7c38.png)
![image](https://user-images.githubusercontent.com/11927929/117112268-189d0300-ad89-11eb-857b-7923d9ae8146.png)

and I fixed the table @albertkol :angel:

2021-05-06 15:41 UTC, lechsandecki commented
+1, looks great. Can we make it live asap, please?

2021-05-06 16:36 UTC, SirSamTumless commented
Hi @lsandecki I don't think it to say "we are slow implementation" in the public channnel. We ask for your review yesterday and you've only just come abck.

2021-05-06 16:52 UTC, lechsandecki approved these changes

2021-05-06 16:53 UTC, merged