Create openstack chart
canonical-web-and-design/ubuntu.com pull request #9816
Opened 2021-05-26 13:11 UTC by petesfrench

## Done

- Creates pie-chart representing number of commit by company to openstack

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/what-is-openstack
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare against [copy-doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit?ts=60a3e5c8#)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9782

2021-05-26 13:11 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9816.demos.haus

2021-05-28 11:00 UTC, anthonydillon commented
I'm off for a week I'm afraid. Mind if this could be assigned to someone else for review.

2021-05-28 12:55 UTC, spencerbygraves commented
@anthonydillon @anasereijo have we done anything similar to this pie chart before? We'll need to look at the colours and hover state I think.

2021-05-28 13:30 UTC, steverydz requested changes
The code looks good. I've left a couple of comments asking for some more descriptive names on variables.

I think this code should be in it's own file and ran through the build pipeline. Doing that would also allow you to import only the parts of d3 that you need.

2021-05-28 13:30 UTC, steverydz commented on templates/openstack/what-is-openstack.html
> +        var div = d3.select("body").append("div")
could this variable reflect the name of the part of the chart it is?

2021-05-28 13:30 UTC, steverydz commented on templates/openstack/what-is-openstack.html
> +        var g = svg.append("g")
could this variable reflect the name of the part of the chart it is?

2021-06-01 08:03 UTC, steverydz commented
After thinking about it I have a couple more comments:
1. You could add `tabindex="0"` to each section of the pie chart. This will allow keyboard users to tab to each section and read the title
2. Even without needing a screen reader it's not very clear which section applies to which company. Perhaps a key would be useful here?

2021-06-01 10:57 UTC, petesfrench commented
@steverydz Thank you for the feedback, I think that's a really good idea to use tabIndex="0". Not sure what we are doing regarding using a key, still waiting on feedback from design.

2021-06-02 10:43 UTC, anasereijo commented
Hey, @petesfrench this is working great!

I have some visual suggestions:

- We built [this page](https://ubuntu.com/desktop/statistics) (ages ago) - can you please use the same colours? I know the graphs are just using orange, aubergine and grey but maybe we can try using whatever we have for the world map? Not sure if I remember well, but I think we picked 2 colours - a dark and a lighter one - and the ones in between are created automatically? Anyway, I'm happy to discuss this with you or pick 9 colours.

- We should use the [Vanilla tooltip](https://vanillaframework.io/docs/patterns/tooltips), if possible.

- can you please close my comments with links to illustrations/logos if you already copied them?

Let me know if it's easier to jump on a call and go through this!
Thanks

2021-06-03 10:42 UTC, anasereijo commented
As discussed with @petesfrench I am turning the table and pie chart into a bar chart. This work is being tracked [here](https://github.com/canonical-web-and-design/web-squad/issues/4166)

2021-06-09 10:35 UTC, steverydz commented
The pie chart is still covered on mobile. I think setting an explicit width and height on it will solve that.

2021-06-22 08:49 UTC, anasereijo commented
@petesfrench is this ready for a design review?

2021-06-22 17:11 UTC, anthonydillon commented
Red hat is off the chart!
![Screenshot_20210622-181014.jpg](https://user-images.githubusercontent.com/1413534/122969986-31876500-d385-11eb-93ee-82fcb2d38604.jpg)

2021-06-28 08:37 UTC, steverydz commented on templates/openstack/what-is-openstack.html
> +      <p>Canonical is the founding member of the foundation, official maintainer and publisher of OpenStack packages on
I've made a couple of suggestions in the copy

2021-06-28 09:07 UTC, steverydz requested changes

2021-06-28 09:07 UTC, steverydz commented on static/js/src/openstack-chart.js
> +  // .attr("viewbox", "0 0" + viewWidth + viewHeight);
Remove commented out code

2021-06-28 09:07 UTC, steverydz commented on static/js/src/openstack-chart.js
> +  var aspectRatio = 0.55;
These `var` can all be `const`

2021-06-28 09:07 UTC, steverydz commented on static/js/src/openstack-chart.js
> +  var totals = d3.sum(data, function (d) {
This `var` can be `const`

2021-06-28 09:07 UTC, steverydz commented on static/js/src/openstack-chart.js
> +  var totals = d3.sum(data, function (d) {
You can use a arrow function here

2021-06-28 09:07 UTC, steverydz commented on static/js/src/openstack-chart.js
> +  data.forEach(function (d) {
You can use a arrow function here

2021-06-28 09:07 UTC, steverydz commented on static/js/src/openstack-chart.js
> +  for (let i = 0; i < data.length; i++) {
you can use `forEach` here instead of a `for` loop

2021-06-29 07:44 UTC, petesfrench commented on templates/openstack/what-is-openstack.html
> +      <p>According to the <a class="p-link--external" href="https://451research.com/search?products=OpenStack">Research
Not sure what the suggested change is here

2021-06-29 08:11 UTC, steverydz commented on templates/openstack/what-is-openstack.html
> +      <p>According to the <a class="p-link--external" href="https://451research.com/search?products=OpenStack">Research
The link text of the link doesn't match the copy doc. In the copy doc it starts with "451"

2021-06-29 08:34 UTC, petesfrench commented
Thanks @steverydz, I made those changes so is ready for another review :+1:

2021-06-29 10:10 UTC, steverydz approved these changes
LGTM, but every instance of the image template seems to have been reformatted to one line? Could you change that back to multiline so it's easier to work with? Other than that, all good!

2021-07-01 14:57 UTC, tytus-kurek commented
@anasereijo this is not compelling anymore. The pie chart from stackanalytics.io includes the "others" field which makes Red Hat's portion smaller and the bar-based approach makes the difference even more significant.

I'd suggest we do the following:
- We mask other contributors with something like "Contributor I", "Contributor II", etc.
- We only mark the Canonical bar aubergine and mark the other bars grey or something like that
- We add the source under the diagram (https://www.stackalytics.io/?release=all&metric=commits) so that when people click on it they see "others" as the biggest contributor and they think it's this 35.7% one.

Those should do the trick.

2021-07-01 15:00 UTC, tytus-kurek requested changes
Comments above.

2021-07-01 15:42 UTC, anasereijo commented
@tytus-kurek sounds good to me, thanks for your review. 

@petesfrench let me know If you need my help on this

2021-07-02 07:54 UTC, petesfrench commented
@anasereijo I made those changes with some design assumptions, can you take a look and let me know what you think

2021-07-02 08:32 UTC, anasereijo commented
Thanks, @petesfrench for making the changes!
please use the `#666666` grey and make Canonical `font-weight: 400;`

I asked @davegoddard42 what he thinks about just using `Source` as a link, let's see what he says :)

2021-07-02 08:58 UTC, anasereijo commented
> Thanks, @petesfrench for making the changes!
> please use the `#666666` grey and make Canonical `font-weight: 400;`
> 
> I asked @davegoddard42 what he thinks about just using just the word `Source` as a link, let's see what he says :)

@peterfrench, please change the link to: `Source: stackalytics` as per @davegoddard42's suggestion. Thanks!

2021-07-07 08:37 UTC, SirSamTumless commented
@tytus-kurek Please re-review this

2021-07-07 08:43 UTC, tytus-kurek commented
@SirSamTumless LGTM. I have a problem assigning `PdM needed` label.

2021-07-07 09:32 UTC, SirSamTumless commented
@petesfrench This is all good to go 🙌

2021-07-08 07:30 UTC, merged