Rebuilds /what-is-openstack page at /openstack
canonical-web-and-design/ubuntu.com pull request #9832
Opened 2021-05-28 07:47 UTC by petesfrench

## Done

- Rebuilds /what-is-openstack page at /openstack

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/what-is-openstack
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare against [copy-doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#heading=h.c45r73q8oci4)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4134

2021-05-28 07:47 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9832.demos.haus

2021-05-28 09:11 UTC, carkod commented on templates/openstack/what-is-openstack.html
> +    </div>
typo `hred`

2021-05-28 09:11 UTC, spencerbygraves commented
Thanks @petesfrench, some changes from me...

Should this section have a title, or something after the ":"?

![image](https://user-images.githubusercontent.com/9105999/119959760-37637380-bf9c-11eb-80fb-c48757e18f3e.png)

The text next to the icons should be white:

![image](https://user-images.githubusercontent.com/9105999/119960072-801b2c80-bf9c-11eb-9a40-4bda54fde272.png)

Can we also remove `is-bordered` from this section please.

Can we use `p-strip is-bordered` for the strip that comes next please ("All the pieces you need to start using OpenStack
")

Can you remove the shadow here please:

![image](https://user-images.githubusercontent.com/9105999/119960497-ed2ec200-bf9c-11eb-8026-52d47a3d993a.png)

Thanks.

2021-05-28 09:13 UTC, tytus-kurek commented
@SirSamTumless 

A couple of issues:

- A link to the National Institute of Standards and Technology is missing
- There is no chart showing Canonical's contribution to OpenStack
- Cisco and Best Buy have some strange logos attached. I'd suggest using the same as at ubuntu.com/openstack
- There is no chart under the "How big is the OpenStack projec?" section
- I'd suggest adding new lines between the content under the "Private cloud", "Network function virtualization", "Bare metal" and "Containers" sections and their CTAs
- "WHITEPAPER", "WEBINAR" and "DATASHEET" under "Learn more about OpenStack" - can we make them white?
- I'd suggest adding new lines between the content under the "Canonical's Charmed OpenStack" and "Ubuntu Server" sections and their CTAs
- It looks like "Growing the cloud?" hasn't been updated to "Public cloud costs increasing?"
- It looks like "Further reading" hasn't been updated

2021-05-28 09:31 UTC, carkod commented
As mentioned above:
- Do we want to add the Canonical's contribution to OpenStack static chart at least?
- "How big is the OpenStack project" is missing?
- Also agree that "WHITEPAPER", "WEBINAR" and "DATASHEET" under "Learn more about OpenStack" is pretty hard to read.
- Missing changes of "Growing the cloud?" and "Further reading"

2021-05-28 10:04 UTC, petesfrench commented
> Thanks @petesfrench, some changes from me...
> 
> Should this section have a title, or something after the ":"?
> 
> ![image](https://user-images.githubusercontent.com/9105999/119959760-37637380-bf9c-11eb-80fb-c48757e18f3e.png)
> 
> The text next to the icons should be white:
> 
> ![image](https://user-images.githubusercontent.com/9105999/119960072-801b2c80-bf9c-11eb-9a40-4bda54fde272.png)
> 
> Can we also remove `is-bordered` from this section please.
> 
> Can we use `p-strip is-bordered` for the strip that comes next please ("All the pieces you need to start using OpenStack
> ")
> 
> Can you remove the shadow here please:
> 
> ![image](https://user-images.githubusercontent.com/9105999/119960497-ed2ec200-bf9c-11eb-8026-52d47a3d993a.png)
> 
> Thanks.

Thanks Spencer, I was making some design assumptions on this one so let me know if there is anything I can change. And for the chart I am waiting for it on another PR.

2021-05-28 10:08 UTC, petesfrench commented
> @SirSamTumless
> 
> A couple of issues:
> 
> * A link to the National Institute of Standards and Technology is missing
> * There is no chart showing Canonical's contribution to OpenStack
> * Cisco and Best Buy have some strange logos attached. I'd suggest using the same as at ubuntu.com/openstack
> * There is no chart under the "How big is the OpenStack projec?" section
> * I'd suggest adding new lines between the content under the "Private cloud", "Network function virtualization", "Bare metal" and "Containers" sections and their CTAs
> * "WHITEPAPER", "WEBINAR" and "DATASHEET" under "Learn more about OpenStack" - can we make them white?
> * I'd suggest adding new lines between the content under the "Canonical's Charmed OpenStack" and "Ubuntu Server" sections and their CTAs
> * It looks like "Growing the cloud?" hasn't been updated to "Public cloud costs increasing?"
> * It looks like "Further reading" hasn't been updated

Hi @tytus-kurek, the 2 charts are being built in seperate PR's. Should I remove the sections entirely?
The two logos on ubuntuu/openstack are out of date, should I create an issue to update to the more recent ones?

2021-05-28 12:16 UTC, tytus-kurek commented
@petesfrench please go ahead and publish with those sections, just make sure you change ":" to "." at the end for now. Regarding logos, yes, we shall update ubuntu.com/openstack too in this case.

2021-05-28 14:59 UTC, spencerbygraves commented
@petesfrench thanks, if you can just make the following small change that would be great:

For the section "All the pieces you need to start using OpenStack", can we use `p-strip is-bordered` please.

Thanks

2021-06-01 09:49 UTC, bethcollins92 requested changes
Looking good! Just some comments in the code, feel free to ping me if you have any questions 👍🏼

2021-06-01 09:49 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +        <a class="p-link--external" href="https://maas.io">Read more about bare metal&nbsp;&rsaquo;</a>
```suggestion
        <a class="p-link--external" href="https://maas.io">Read more about bare metal</a>
```

2021-06-01 09:49 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +          {{ image (
This is a different image on the copy doc - (The ubuntu logo)

2021-06-01 09:49 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <table>
This table is now a child of the row, (only cols should be children of rows). You could enclose it in the `col-9` or make a new row with whatever col width you need

2021-06-01 09:49 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <div class="u-align--center u-hide--small">
same here (should be a new row)

2021-06-01 09:49 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +      <li class="col-2 col-small-2 col-medium-2">
There is a logo pattern you can use on Vanilla https://vanillaframework.io/docs/patterns/logo-section

2021-06-01 09:49 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <div class="row p-divider u-no-padding--left u-no-padding--right">
I don't think you need the `u-fixed-width` class and the `row` - you can just use the row. Or you can do it like you do on line 687

2021-06-01 09:49 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +      <p class="p-card__content">Canonical’s Charmed OpenStack is a pure upstream OpenStack distribution engineered for the best price-performance with full enterprise support.</p>
This sometimes happens when you copy and paste from the copy doc, but the quotes and apostrophes should all be straight 
```suggestion
      <p class="p-card__content">Canonical's Charmed OpenStack is a pure upstream OpenStack distribution engineered for the best price-performance with full enterprise support.</p>
```

2021-06-03 12:41 UTC, bethcollins92 requested changes
Not far off! Just a few col and row nesting corrections. Take a look here https://vanillaframework.io/docs/patterns/grid

2021-06-03 12:41 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <div class="col-12">
this `col-12` needs to be in a new row, as the row it's currently in is already populated with a `col-9`

2021-06-03 12:41 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <div class="row u-align--center u-hide--small">
This `row` is a child of another `row` which isn't semantically correct - you need to close the previous `row` div before opening another one. Also a child of this is a `<p>` - it needs to be a `col`

2021-06-03 12:41 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <div class="p-logo-section__items">
this is a child of the row so it needs to be a col, it should work in the same div

2021-06-03 12:41 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +  <div class="row p-logo-section">
https://vanillaframework.io/docs/patterns/logo-section - take a look how they do it here with the `u-fixed-width` class and the logo section

2021-06-03 12:41 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +        <ul class="p-list">
a `<ul>` element shouldn't go inside a `<p>` - see here https://bytes.com/topic/html-css/answers/153770-acceptable-put-ul-inside-paragraph. You can close the `<p>` before hand.

2021-06-03 12:41 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <p>
Please move this inside the `div` on the line above

2021-06-03 12:41 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <div class="row p-divider u-no-padding--left u-no-padding--right">
@petesfrench have you fixed this? it looks the same so not sure if github is not showing the new commit or maybe you missed it (feel free to reach out if you're not sure what I mean)

2021-06-03 14:10 UTC, bethcollins92 approved these changes
Niice - we are pretty much there. Just make those final changes and you're good to go

2021-06-03 14:10 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +  <p>
This can be moved to inside the div on line 103 as here it's a child of a row

2021-06-03 14:10 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +    <div class="col-12 p-logo-section__items">
this col-12 is in the same row as the col-8. Maximum cols per row is 12. Can you not use `u-fixed-width`?

2021-06-03 14:10 UTC, bethcollins92 commented on templates/openstack/what-is-openstack.html
> +      <h2>Who uses OpenStack?</h2>
this `p-logo-section` is correct so just copy this one for the one above

2021-06-03 15:39 UTC, merged