9751 cis page build
canonical-web-and-design/ubuntu.com pull request #9844
Opened 2021-06-01 09:49 UTC by petesfrench

## Done

- Builds /security/cis page

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cis
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare against [copy-doc](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit#)

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9751

2021-06-01 09:49 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9844.demos.haus

2021-06-01 11:40 UTC, spencerbygraves commented
Thanks @petesfrench, can we do something to avoid the icon widow? Perhaps a copy change @SirSamTumless?

![image](https://user-images.githubusercontent.com/9105999/120317368-719f7e80-c2d6-11eb-81d1-804a4153f6fd.png)

Also, can we keep the tick icons consistent with the [other security page](https://github.com/canonical-web-and-design/ubuntu.com/pull/9821) please.

2021-06-03 14:21 UTC, bethcollins92 requested changes
Nice! 👍🏼  - just some small changes. (And make sure to remove the changes from the livepatch page)

2021-06-03 14:21 UTC, bethcollins92 commented on templates/security/cis.html
> +    <table>
Make sure this table is inside a `u-fixed-width` or a `row` and `col`

2021-06-03 14:21 UTC, bethcollins92 commented on templates/security/cis.html
> +
Here you can copy the marketo info from the bottom of the [/security/fips](https://github.com/canonical-web-and-design/ubuntu.com/pull/9852/files) page

2021-06-03 15:10 UTC, bethcollins92 commented on templates/openstack/cis.html
> +      <a href="/support#get-in-touch" class="p-button--positive">Access the tooling for audit and automated CIS compliance</a>
```suggestion
      <a href="/support/get-in-touch" class="p-button--positive">Access the tooling for audit and automated CIS compliance</a>
```

2021-06-03 15:12 UTC, bethcollins92 requested changes
Looking good! Can you check the rows and cols again and let me know then I'll have another look!

2021-06-03 15:12 UTC, bethcollins92 commented on templates/openstack/cis.html
> +      <a href="/support#get-in-touch" class="p-button--positive">Access the tooling for audit and automated CIS compliance</a>
```suggestion
      <a href="/support/get-in-touch" class="p-button--positive js-invoke-modal">Access the tooling for audit and automated CIS compliance</a>
```

2021-06-03 15:12 UTC, bethcollins92 commented on templates/openstack/cis.html
> +
copy the marketo info from the bottom of this [page](https://github.com/canonical-web-and-design/ubuntu.com/pull/9852/files)

2021-06-04 14:05 UTC, bethcollins92 approved these changes
LGTM 👍🏼  Can you just add the modal class to the button and let me know when you've done it, I'll check that before I give the QA +1

2021-06-04 14:05 UTC, bethcollins92 commented on templates/security/cis.html
> +      <a href="/support/get-in-touch" class="p-button--positive">Access the tooling for audit and automated CIS compliance</a>
Can you add this `js-invoke-modal` class to the button, it should be a pop up modal when clicked. 
```suggestion
      <a href="/support/get-in-touch" class="p-button--positive js-invoke-modal">Access the tooling for audit and automated CIS compliance</a>
```

2021-06-04 14:13 UTC, anasereijo commented
@petesfrench sorry last minute change:
can you remove the italics from 'Comply with the most widely accepted baseline' and make it a <h4>? Thanks

2021-06-04 14:42 UTC, bethcollins92 commented
Nice! LGTM

2021-06-04 15:11 UTC, merged

2021-06-05 07:43 UTC, anthonydillon commented on templates/security/cis.html
> +      <a href="/support/get-in-touch" class="p-button--positive js-invoke-modal">Access the tooling for audit and automated CIS compliance</a>
Is this an actual page? The href acts as a no-js fall back. It should probably go to "/support/contact-us"

2021-06-05 07:43 UTC, anthonydillon commented on templates/security/cis.html
> +<div class="u-hide" id="contact-form-container" data-form-location="/shared/forms/interactive/support" data-form-id="1257" data-lp-id="2154" data-return-url="https://www.ubuntu.com/contact-us/form/th
I think the return URL here should be to support/thank-you