Add link to the study labs from the study materials index page
canonical-web-and-design/ubuntu.com pull request #9929
Opened 2021-06-21 21:38 UTC by jpmartinspt

## Done
Add link to the study labs from the study materials index page

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Go to `/study/materials`
- Click the purchase study labs button and:
  - If you have the enrolment you should be redirected to the course in the EDX platform.
  - If you don't have the enrolment you should be redirected to `/cube/microcerts` which is where the purchase will be done from in the future.

## Issue / Card

Fixes #9867
Fixes #9913

2021-06-21 21:38 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9929.demos.haus

2021-06-21 21:47 UTC, jpmartinspt commented
@KellenRenshaw can you please QA this?

2021-06-23 16:18 UTC, KellenRenshaw commented
The button works as described. Is it possible for the button's text to change based on the enrollment status?

Right now we have a "Purchase Study Lab access" button that may or may not lead you to the purchase page. Ideally, if the user has the enrollment, it would change to "Access Study Lab" or similar.

2021-06-24 17:52 UTC, anthonydillon requested changes
Few questions in the code

2021-06-24 17:52 UTC, anthonydillon commented on templates/cube/study/index.md
> +<a class="p-button--positive js-study-button"><i class="p-icon--spinner u-animation--spin is-light"></i></a>
Could you add a `u-hide` class with an empty href and have the JS remove the class on load?

2021-06-24 17:52 UTC, anthonydillon commented on templates/cube/study/index.md
> +<a class="p-button--positive js-study-button"><i class="p-icon--spinner u-animation--spin is-light"></i></a>
Can you add the words "Loading" inside the icon so there is some content please

2021-06-24 17:52 UTC, anthonydillon commented on templates/cube/study/index.md
> +  fetch("study/labs")
Shouldn't this be "/cube/study/labs" to be more specific. Incase this code moves?

2021-06-24 17:52 UTC, anthonydillon commented on templates/cube/study/index.md
> +      button.remove()
Could we provide a more useful thing to the user if this fails unexpectedly. For example, disable the button and change text to error message?

2021-06-24 18:36 UTC, jpmartinspt commented
@anthonydillon addressed your comments.
@KellenRenshaw the button text should change now.

2021-06-24 18:40 UTC, anthonydillon approved these changes
LGTM thanks

2021-06-24 18:58 UTC, KellenRenshaw commented
+1, LGTM!

2021-06-24 23:42 UTC, merged