Pre-fill the product selector with a free trial
canonical-web-and-design/ubuntu.com pull request #9963
Opened 2021-06-28 15:05 UTC by ClementChaumel

## Done

- Added the ability to prepop the wizard with a query param

## QA

- go here http://0.0.0.0:8001/advantage/subscribe?test_backend=true&esm_apps=true&free_trial=uai-essential-physical&quantity=222
- experiment with different ids and quantities in the url
- check that the selected product and quantity matches

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9493

## List of product IDs you can use
`uaa-essential`
`uaa-essential-virtual`
`uaia-essential-physical`
`uaia-essential-virtual`
`uaa-advanced`
`uaa-advanced-virtual`
`uaa-essential-desktop`
`uaa-standard`
`uaa-standard-virtual`
`uaia-advanced-physical`
`uaia-advanced-virtual`
`uai-advanced-desktop`
`uai-advanced-physical`
`uai-advanced-virtual`
`uaia-standard-physical`
`uaia-standard-virtual`
`uai-essential-desktop`
`uai-essential-physical`
`uai-essential-virtual`
`uai-standard-desktop`
`uai-standard-physical`
`uai-standard-virtual`

2021-06-28 15:05 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9963.demos.haus

2021-06-28 15:21 UTC, anthonydillon commented
## QA
- Tried it with different quantities and products (All worked fine)
- Tried an [unknown product name and it defaulted to UA Infrastructure - Advanced (Physical) :man_shrugging: 
- Tried a [minus value on the quantity](https://ubuntu-com-9963.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true&free_trial=&quantity=-12) (:fire: Broke the UI)

2021-06-28 15:22 UTC, anthonydillon requested changes
No validation on the quantity input via the URL

2021-06-29 10:50 UTC, anthonydillon approved these changes
Works perfectly thanks @ClementChaumel!

One small nik but not a blocker is could you safe render the title to fix the `&amp;` in the screenshot:
![image](https://user-images.githubusercontent.com/1413534/123785273-4194cc80-d8d0-11eb-9958-94e315a1c1a2.png)

2021-06-29 12:58 UTC, ClementChaumel commented
> safe render

Hey, I'm not sure how to do that other than using `dangerouslySetInnerHTML`. do you know of a better way?

2021-06-30 08:03 UTC, anthonydillon commented
Sure I'll take a look today but let's do it as a follow up. I'll create an issue.

2021-06-30 16:09 UTC, merged