add link to survey
canonical-web-and-design/ubuntu.com pull request #9965
Opened 2021-06-28 16:26 UTC by evilnick

## Done

Adds a link from Kubernetes docs to survey report.
Alex wants this link to go live by/on 29th June

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)

2021-06-28 16:26 UTC, webteam-app commented
Demo starting at https://ubuntu-com-9965.demos.haus

2021-06-28 19:51 UTC, anthonydillon requested changes
One small issue in the code

2021-06-28 19:51 UTC, anthonydillon commented on templates/kubernetes/docs/index.md
> +      <p>How Devs, DevOps and businesses <em>really</em> use Kubernetes: <a href="https://juju.is/cloud-native-kubernetes-usage-report-2021">Read the latest industry report</a>
Missing ending `</p>`

2021-06-29 08:34 UTC, evilnick commented on templates/kubernetes/docs/index.md
> +      <p>How Devs, DevOps and businesses <em>really</em> use Kubernetes: <a href="https://juju.is/cloud-native-kubernetes-usage-report-2021">Read the latest industry report</a>
fixed thanks!

2021-06-29 10:47 UTC, anthonydillon approved these changes
So you have :+1: thanks @evilnick

2021-06-29 10:47 UTC, merged